/**
 * Registry of all enemy templates, keyed by snake_case enemy ID.
 *
 * Each entry is a template used to instantiate enemy encounters. Optional
 * fields (aoeAttack, statusProcs, callsForHelp, description) may be absent
 * on entries that do not require them.
 *
 * @type {Object.<string, {
 *   id: string,
 *   name: string,
 *   level: number,
 *   hp: number,
 *   atk: number,
 *   ac: number,
 *   xp: number,
 *   type: string,
 *   isRare: boolean,
 *   isUndead: boolean,
 *   aoeAttack?: boolean,
 *   statusProcs?: Array<{chance: number, type: string, damage?: number, duration?: number}>,
 *   lootTable: Array<{itemId: string, chance: number, quantity: [number, number]}>,
 *   callsForHelp?: {chance: number, addIds: Array<string>},
 *   description?: string
 * }>}
 *
 * @property {string}           id            - snake_case identifier matching the registry key.
 * @property {string}           name          - Display name shown to the player.
 * @property {number}           level         - Enemy level; used for con-color calculation and XP scaling.
 * @property {number}           hp            - Base hit points.
 * @property {number}           atk           - Base attack value used in damage rolls.
 * @property {number}           ac            - Armor class; reduces incoming damage.
 * @property {number}           xp            - Base experience points awarded on kill.
 * @property {string}           type          - Enemy category, e.g. 'animal', 'humanoid', 'undead'.
 * @property {boolean}          isRare        - If true, this is a named/rare spawn with special loot.
 * @property {boolean}          isUndead      - If true, holy abilities deal bonus damage to this enemy.
 * @property {boolean}          [aoeAttack]   - If true, the enemy uses sweeping AoE attacks.
 * @property {Array<object>}    [statusProcs] - On-hit proc effects; each entry has chance, type, and optional damage/duration.
 * @property {Array<object>}    lootTable     - Possible item drops; each entry has itemId, chance (0–1), and quantity [min, max].
 * @property {object}           [callsForHelp]- Optional call-for-help behaviour: {chance, addIds[]}.
 * @property {string}           [description] - Optional lore/flavour text for the enemy.
 */
const ENEMIES = {
  mangy_rat: {
    id: 'mangy_rat',
    name: 'Mangy Rat',
    level: 1,
    hp: 15,
    atk: 2,
    ac: 1,
    xp: 500,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'rat_pelt', chance: 0.5, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.5, quantity: [1, 4] },
      { itemId: 'silver_coin', chance: 0.05, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'A flea-ridden rat barely worth drawing your weapon for.',
  },

  giant_rat: {
    id: 'giant_rat',
    name: 'Giant Rat',
    level: 2,
    hp: 25,
    atk: 3,
    ac: 3,
    xp: 800,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'rat_pelt', chance: 0.5, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.6, quantity: [1, 5] },
      { itemId: 'silver_coin', chance: 0.07, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Larger than its mangy cousin, this rat has learned to survive by being aggressive.',
  },

  large_rat: {
    id: 'large_rat',
    name: 'Large Rat',
    level: 3,
    hp: 35,
    atk: 5,
    ac: 4,
    xp: 1200,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'rat_pelt', chance: 0.5, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [1, 6] },
      { itemId: 'silver_coin', chance: 0.08, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'An unnaturally large rodent with yellowed teeth and a vicious temperament.',
  },

  fire_beetle: {
    id: 'fire_beetle',
    name: 'Fire Beetle',
    level: 3,
    hp: 30,
    atk: 5,
    ac: 5,
    xp: 1200,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'fire_beetle_eye', chance: 0.7, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.55, quantity: [1, 5] },
      { itemId: 'silver_coin', chance: 0.07, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Its abdomen glows with a bioluminescent orange light, prized by alchemists.',
  },

  snake: {
    id: 'snake',
    name: 'Snake',
    level: 2,
    hp: 20,
    atk: 4,
    ac: 2,
    xp: 800,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'snake_scale', chance: 0.6, quantity: [1, 3] },
      { itemId: 'copper_coin', chance: 0.5, quantity: [1, 4] },
      { itemId: 'silver_coin', chance: 0.06, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'A common hill snake that blends expertly into the tall grass.',
  },

  king_snake: {
    id: 'king_snake',
    name: 'King Snake',
    level: 5,
    hp: 65,
    atk: 9,
    ac: 8,
    xp: 2500,
    type: 'animal',
    isRare: true,
    isUndead: false,
    lootTable: [
      { itemId: 'snake_scale', chance: 0.6, quantity: [2, 5] },
      { itemId: 'copper_coin', chance: 0.7, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.15, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A massive serpent that lords over the lesser snakes of the hills. Rarely seen.',
  },

  bat: {
    id: 'bat',
    name: 'Bat',
    level: 2,
    hp: 18,
    atk: 3,
    ac: 2,
    xp: 700,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'bat_wing', chance: 0.6, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.5, quantity: [1, 3] },
      { itemId: 'silver_coin', chance: 0.05, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'A squealing cave bat drawn out into the hills at dusk.',
  },

  giant_bat: {
    id: 'giant_bat',
    name: 'Giant Bat',
    level: 5,
    hp: 60,
    atk: 8,
    ac: 6,
    xp: 2200,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'bat_wing', chance: 0.8, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [2, 7] },
      { itemId: 'silver_coin', chance: 0.12, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'With a wingspan that blocks out the moon, this beast is a terror of the night sky.',
  },

  gnoll_pup: {
    id: 'gnoll_pup',
    name: 'Gnoll Pup',
    level: 3,
    hp: 40,
    atk: 6,
    ac: 5,
    xp: 1500,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_tooth', chance: 0.5, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [1, 6] },
      { itemId: 'silver_coin', chance: 0.08, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Young and reckless, gnoll pups are eager to prove themselves through violence.',
  },

  gnoll: {
    id: 'gnoll',
    name: 'Gnoll',
    level: 5,
    hp: 75,
    atk: 10,
    ac: 8,
    xp: 3000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.4, quantity: [1, 1] },
      { itemId: 'rusty_short_sword', chance: 0.1, quantity: [1, 1] },
      { itemId: 'gnoll_tooth', chance: 0.6, quantity: [1, 3] },
      { itemId: 'copper_coin', chance: 0.75, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.12, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'A full-grown gnoll warrior, hyena-headed and wielding crude weapons with brutal efficiency.',
  },

  gnoll_scout: {
    id: 'gnoll_scout',
    name: 'Gnoll Scout',
    level: 7,
    hp: 100,
    atk: 14,
    ac: 10,
    xp: 4500,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.5, quantity: [1, 2] },
      { itemId: 'gnoll_slayer', chance: 0.05, quantity: [1, 1] },
      { itemId: 'tarnished_axe', chance: 0.1, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.78, quantity: [3, 10] },
      { itemId: 'silver_coin', chance: 0.15, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A quick and cunning gnoll that ranges far ahead of the pack to ambush unwary travelers.',
  },

  gnoll_watcher: {
    id: 'gnoll_watcher',
    name: 'Gnoll Watcher',
    level: 8,
    hp: 120,
    atk: 16,
    ac: 12,
    xp: 5500,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.55, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.78, quantity: [3, 12] },
      { itemId: 'silver_coin', chance: 0.17, quantity: [1, 3] },
    ],
    statusEffects: [],
    callsForHelp: { chance: 0.55, addIds: ['gnoll_pup', 'gnoll'] },
    description: 'Stationed at the perimeter of the gnoll camp, the watcher calls out with a piercing howl when intruders approach.',
  },

  gnoll_hunter: {
    id: 'gnoll_hunter',
    name: 'Gnoll Hunter',
    level: 9,
    hp: 145,
    atk: 18,
    ac: 14,
    xp: 7000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.6, quantity: [1, 3] },
      { itemId: 'tarnished_axe', chance: 0.15, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.8, quantity: [4, 14] },
      { itemId: 'silver_coin', chance: 0.2, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'An elite gnoll tracker who moves silently despite its bulk, trapping prey with practiced cruelty.',
  },

  gray_wolf: {
    id: 'gray_wolf',
    name: 'Gray Wolf',
    level: 4,
    hp: 55,
    atk: 8,
    ac: 6,
    xp: 2000,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'wolf_pelt', chance: 0.65, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.6, quantity: [1, 6] },
      { itemId: 'silver_coin', chance: 0.09, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'A lean pack hunter with pale gray fur and intelligent amber eyes.',
  },

  rabid_wolf: {
    id: 'rabid_wolf',
    name: 'Rabid Wolf',
    level: 6,
    hp: 85,
    atk: 12,
    ac: 8,
    xp: 3500,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'wolf_pelt', chance: 0.75, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [2, 7] },
      { itemId: 'silver_coin', chance: 0.11, quantity: [1, 2] },
    ],
    statusEffects: [
      { type: 'poison', chance: 0.2, duration: 10000, damage: 3 },
    ],
    description: 'Foam flecks its muzzle and its eyes burn with mindless fury — approach only if you have no other choice.',
  },

  brown_bear: {
    id: 'brown_bear',
    name: 'Brown Bear',
    level: 6,
    hp: 90,
    atk: 11,
    ac: 9,
    xp: 3800,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'bear_pelt', chance: 0.6, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [1, 7] },
      { itemId: 'silver_coin', chance: 0.11, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'A territorial brown bear that will charge anything that wanders too close to its den.',
  },

  grizzly_bear: {
    id: 'grizzly_bear',
    name: 'Grizzly Bear',
    level: 8,
    hp: 130,
    atk: 17,
    ac: 13,
    xp: 6000,
    type: 'animal',
    isRare: false,
    isUndead: false,
    enrages: true,
    lootTable: [
      { itemId: 'bear_pelt', chance: 0.75, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.7, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.15, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'Massive and temperamental, the grizzly bear is the apex predator of the Qeynos Hills.',
  },

  decaying_skeleton: {
    id: 'decaying_skeleton',
    name: 'Decaying Skeleton',
    level: 5,
    hp: 70,
    atk: 9,
    ac: 7,
    xp: 2800,
    type: 'undead',
    isRare: false,
    isUndead: true,
    lootTable: [
      { itemId: 'bone_chips', chance: 0.8, quantity: [1, 3] },
      { itemId: 'cracked_staff', chance: 0.05, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.6, quantity: [1, 5] },
      { itemId: 'silver_coin', chance: 0.08, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Animated by dark magic, this crumbling skeleton rattles and scrapes as it shambles toward the living.',
  },

  putrid_skeleton: {
    id: 'putrid_skeleton',
    name: 'Putrid Skeleton',
    level: 7,
    hp: 95,
    atk: 13,
    ac: 10,
    xp: 4200,
    type: 'undead',
    isRare: false,
    isUndead: true,
    lootTable: [
      { itemId: 'bone_chips', chance: 0.9, quantity: [1, 4] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [1, 6] },
      { itemId: 'silver_coin', chance: 0.1, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'Older and more powerful than a decaying skeleton, its bones are stained black with necrotic energy.',
  },

  dread_corpse: {
    id: 'dread_corpse',
    name: 'Dread Corpse',
    level: 8,
    hp: 115,
    atk: 15,
    ac: 11,
    xp: 5200,
    type: 'undead',
    isRare: false,
    isUndead: true,
    lootTable: [
      { itemId: 'bone_chips', chance: 0.85, quantity: [2, 5] },
      { itemId: 'copper_coin', chance: 0.68, quantity: [2, 7] },
      { itemId: 'silver_coin', chance: 0.12, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'A bloated, shambling horror whose very presence dims the light and chills the blood.',
  },

  will_o_wisp: {
    id: 'will_o_wisp',
    name: "Will O' Wisp",
    level: 10,
    hp: 160,
    atk: 20,
    ac: 15,
    xp: 8000,
    type: 'magical',
    isRare: false,
    isUndead: false,
    magicResist: 50,
    enrages: true,
    aoeAttack: true,
    lootTable: [
      { itemId: 'copper_coin', chance: 0.7, quantity: [3, 8] },
      { itemId: 'silver_coin', chance: 0.2, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A drifting orb of cold, eldritch light that lures travelers off the path to their doom. Highly resistant to magic.',
  },

  bandit: {
    id: 'bandit',
    name: 'Bandit',
    level: 6,
    hp: 80,
    atk: 12,
    ac: 9,
    xp: 3300,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'copper_coin', chance: 0.9, quantity: [3, 15] },
      { itemId: 'silver_coin', chance: 0.3, quantity: [1, 5] },
      { itemId: 'rusty_short_sword', chance: 0.15, quantity: [1, 1] },
    ],
    statusEffects: [],
    callsForHelp: { chance: 0.50, addIds: ['bandit'] },
    description: 'A desperate cutthroat who preys on travelers along the roads outside Qeynos.',
  },

  hadden: {
    id: 'hadden',
    name: 'Hadden',
    level: 12,
    hp: 250,
    atk: 25,
    ac: 20,
    xp: 15000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    enrages: true,
    lootTable: [
      { itemId: 'fishbone_earring', chance: 1.0, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 1.0, quantity: [5, 20] },
    ],
    statusEffects: [],
    description: 'A wandering hermit whose strange earring is said to carry magical properties. He does not part with it willingly.',
  },

  varsoon_the_undying: {
    id: 'varsoon_the_undying',
    name: 'Varsoon the Undying',
    level: 12,
    hp: 280,
    atk: 28,
    ac: 18,
    xp: 17500,
    type: 'undead',
    isRare: true,
    isUndead: true,
    enrages: true,
    aoeAttack: true,
    lootTable: [
      { itemId: 'glowing_black_stone', chance: 1.0, quantity: [1, 1] },
      { itemId: 'bone_chips', chance: 1.0, quantity: [5, 10] },
      { itemId: 'silver_coin', chance: 0.8, quantity: [3, 10] },
    ],
    statusEffects: [],
    description: 'An ancient necromancer who cheated death one too many times. Now he IS death, wandering the hills in a decayed body held together by sheer hatred.',
  },

  // ─── BLACKBURROW ENEMIES ─────────────────────────────────────────────────────

  a_scrawny_gnoll: {
    id: 'a_scrawny_gnoll',
    name: 'a scrawny gnoll',
    level: 4,
    hp: 50,
    atk: 7,
    ac: 5,
    xp: 1500,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_tooth', chance: 0.4, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.6, quantity: [2, 6] },
    ],
    statusEffects: [],
    description: 'A runty, underfed gnoll barely able to hold its weapon steady.',
  },

  scrawny_gnoll: {
    id: 'scrawny_gnoll',
    name: 'Scrawny Gnoll',
    level: 4,
    hp: 50,
    atk: 7,
    ac: 6,
    xp: 1800,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_tooth', chance: 0.5, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.7, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.1, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: "Underfed and desperate, these young gnolls are the first line of Blackburrow's defense.",
  },

  a_gnoll_guard: {
    id: 'a_gnoll_guard',
    name: 'a gnoll guard',
    level: 6,
    hp: 80,
    atk: 11,
    ac: 8,
    xp: 3000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'copper_coin', chance: 0.7, quantity: [1, 8] },
      { itemId: 'silver_coin', chance: 0.09, quantity: [1, 1] },
    ],
    statusEffects: [],
    callsForHelp: { chance: 0.50, addIds: ['a_scrawny_gnoll'] },
    description: 'A lean, mangy gnoll barely past puphood. Dangerous in numbers.',
  },

  burly_gnoll: {
    id: 'burly_gnoll',
    name: 'Burly Gnoll',
    level: 7,
    hp: 105,
    atk: 15,
    ac: 11,
    xp: 5000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.4, quantity: [1, 1] },
      { itemId: 'gnoll_tooth', chance: 0.5, quantity: [1, 3] },
      { itemId: 'copper_coin', chance: 0.75, quantity: [3, 10] },
      { itemId: 'silver_coin', chance: 0.15, quantity: [1, 3] },
      { itemId: 'bb_gnoll_guard_shield', chance: 0.05, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'A hardened gnoll patrolling the tunnels, alert for intruders.',
  },

  a_burly_gnoll: {
    id: 'a_burly_gnoll',
    name: 'a burly gnoll',
    level: 8,
    hp: 115,
    atk: 15,
    ac: 11,
    xp: 5000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.55, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.8, quantity: [3, 12] },
      { itemId: 'silver_coin', chance: 0.14, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'Thick-necked and barrel-chested, this gnoll hits harder than it looks.',
  },

  gnoll_guard: {
    id: 'gnoll_guard',
    name: 'Gnoll Guard',
    level: 9,
    hp: 140,
    atk: 19,
    ac: 15,
    xp: 7500,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.5, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.8, quantity: [4, 12] },
      { itemId: 'silver_coin', chance: 0.2, quantity: [1, 4] },
      { itemId: 'tarnished_axe', chance: 0.08, quantity: [1, 1] },
    ],
    statusEffects: [],
    // burly_gnoll and a_burly_gnoll are two distinct difficulty variants of the same species
    callsForHelp: { chance: 0.55, addIds: ['burly_gnoll', 'a_burly_gnoll'] },
    description: 'Built like a wall of fur and muscle, the burly gnoll is no mere sentry.',
  },

  a_gnoll_shaman: {
    id: 'a_gnoll_shaman',
    name: 'a gnoll shaman',
    level: 9,
    hp: 100,
    atk: 13,
    ac: 9,
    xp: 5500,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    aoeAttack: true,
    statusProcs: [
      { type: 'poison', chance: 0.2, duration: 12000, damage: 8 },
    ],
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.5, quantity: [1, 2] },
      { itemId: 'gnoll_shaman_beads', chance: 0.3, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.8, quantity: [4, 15] },
      { itemId: 'silver_coin', chance: 0.22, quantity: [1, 4] },
      { itemId: 'gnoll_shaman_staff', chance: 0.06, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Muttering dark incantations, this gnoll shaman channels the foul powers of his ancestors.',
  },

  a_gnoll_guard_elite: {
    id: 'a_gnoll_guard_elite',
    name: 'a gnoll guard elite',
    level: 11,
    hp: 160,
    atk: 20,
    ac: 15,
    xp: 8000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.6, quantity: [1, 3] },
      { itemId: 'copper_coin', chance: 0.85, quantity: [5, 15] },
      { itemId: 'silver_coin', chance: 0.3, quantity: [1, 5] },
      { itemId: 'gold_coin', chance: 0.05, quantity: [1, 1] },
      { itemId: 'elite_gnoll_helm', chance: 0.05, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Veteran soldiers who have survived countless raids. Their armor is dented but their resolve is iron.',
  },

  a_giant_plague_rat: {
    id: 'a_giant_plague_rat',
    name: 'a giant plague rat',
    level: 5,
    hp: 70,
    atk: 9,
    ac: 6,
    xp: 2200,
    type: 'animal',
    isRare: false,
    isUndead: false,
    statusProcs: [
      { type: 'disease', chance: 0.15, duration: 15000, damage: 5 },
    ],
    lootTable: [
      { itemId: 'rat_pelt', chance: 0.6, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.6, quantity: [2, 7] },
      { itemId: 'silver_coin', chance: 0.08, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'Enormous rats that have fed on gnoll refuse and grown bloated with pestilence.',
  },

  a_giant_snake_bb: {
    id: 'a_giant_snake_bb',
    name: 'a giant snake',
    level: 7,
    hp: 90,
    atk: 12,
    ac: 8,
    xp: 4000,
    type: 'animal',
    isRare: false,
    isUndead: false,
    statusProcs: [
      { type: 'poison', chance: 0.25, duration: 10000, damage: 10 },
    ],
    lootTable: [
      { itemId: 'snake_scale', chance: 0.7, quantity: [2, 5] },
      { itemId: 'copper_coin', chance: 0.6, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.1, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: "Massive constrictors that lurk in Blackburrow's flooded lower passages.",
  },

  gnoll_shaman: {
    id: 'gnoll_shaman',
    name: 'Gnoll Shaman',
    level: 10,
    hp: 155,
    atk: 18,
    ac: 13,
    xp: 8500,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.6, quantity: [1, 2] },
      { itemId: 'runed_totem_staff', chance: 0.08, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.8, quantity: [4, 14] },
      { itemId: 'silver_coin', chance: 0.2, quantity: [1, 3] },
    ],
    statusEffects: [
      { type: 'poison', chance: 0.15, duration: 12000, damage: 4 },
    ],
    description: 'A fetish-adorned gnoll witch doctor. Its bone rattles herald a hex.',
  },

  gnoll_commander: {
    id: 'gnoll_commander',
    name: 'Gnoll Commander',
    level: 12,
    hp: 210,
    atk: 24,
    ac: 18,
    xp: 12000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    enrages: true,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.7, quantity: [2, 4] },
      { itemId: 'spiked_collar', chance: 0.12, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.85, quantity: [5, 20] },
      { itemId: 'silver_coin', chance: 0.3, quantity: [2, 5] },
      { itemId: 'gold_coin', chance: 0.08, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Commands the gnoll forces in the deep tunnels with a bark that makes even burly gnolls flinch.',
  },

  gnoll_high_shaman: {
    id: 'gnoll_high_shaman',
    name: 'Gnoll High Shaman',
    level: 14,
    hp: 260,
    atk: 27,
    ac: 20,
    xp: 16000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    magicResist: 25,
    enrages: true,
    aoeAttack: true,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.75, quantity: [2, 5] },
      { itemId: 'runed_totem_staff', chance: 0.15, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.5, quantity: [3, 8] },
      { itemId: 'gold_coin', chance: 0.15, quantity: [1, 2] },
    ],
    statusEffects: [
      { type: 'poison', chance: 0.25, duration: 15000, damage: 6 },
    ],
    description: 'The spiritual leader of the Blackburrow pack. Radiates dark power.',
  },

  giant_plague_rat: {
    id: 'giant_plague_rat',
    name: 'Giant Plague Rat',
    level: 5,
    hp: 70,
    atk: 10,
    ac: 7,
    xp: 2600,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'rat_pelt', chance: 0.6, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.7, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.08, quantity: [1, 1] },
    ],
    statusEffects: [
      { type: 'poison', chance: 0.3, duration: 10000, damage: 3 },
    ],
    description: 'A bloated, diseased rat infesting the lower tunnels of Blackburrow. Its bite festers.',
  },

  giant_snake_bb: {
    id: 'giant_snake_bb',
    name: 'Giant Snake',
    level: 8,
    hp: 125,
    atk: 16,
    ac: 12,
    xp: 6000,
    type: 'animal',
    isRare: true,
    isUndead: false,
    lootTable: [
      { itemId: 'snake_scale', chance: 0.7, quantity: [2, 5] },
      { itemId: 'giant_snake_fang', chance: 0.6, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.7, quantity: [3, 10] },
      { itemId: 'silver_coin', chance: 0.15, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A massive constrictor lurking in the flooded lower pit of Blackburrow.',
  },

  lord_elgnub: {
    id: 'lord_elgnub',
    name: 'Lord Elgnub',
    level: 15,
    hp: 320,
    atk: 32,
    ac: 22,
    xp: 22000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    enrages: true,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 1.0, quantity: [2, 4] },
      { itemId: 'elgnubs_gnoll_hide_belt', chance: 0.3, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 1.0, quantity: [10, 30] },
      { itemId: 'silver_coin', chance: 0.8, quantity: [5, 15] },
      { itemId: 'gold_coin', chance: 0.2, quantity: [1, 5] },
      { itemId: 'lords_insignia_ring', chance: 0.15, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Lord Elgnub rules the deepest warrens of Blackburrow with absolute authority. His very name causes lesser gnolls to tremble.',
  },

  gnoll_high_shaman_bb: {
    id: 'gnoll_high_shaman_bb',
    name: 'Gnoll High Shaman',
    level: 12,
    hp: 220,
    atk: 22,
    ac: 16,
    xp: 14000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    enrages: true,
    aoeAttack: true,
    statusProcs: [
      { type: 'poison', chance: 0.35, duration: 16000, damage: 12 },
    ],
    lootTable: [
      { itemId: 'gnoll_shaman_beads', chance: 0.8, quantity: [1, 2] },
      { itemId: 'gnoll_high_shaman_staff', chance: 0.25, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 1.0, quantity: [8, 25] },
      { itemId: 'silver_coin', chance: 0.7, quantity: [4, 12] },
      { itemId: 'gold_coin', chance: 0.15, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'The spiritual leader of the Blackburrow gnolls, whose curses linger long after his death.',
  },

  gnoll_brewer: {
    id: 'gnoll_brewer',
    name: 'Gnoll Brewer',
    level: 7,
    hp: 95,
    atk: 11,
    ac: 8,
    xp: 4500,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    lootTable: [
      { itemId: 'blackburrow_stout', chance: 0.9, quantity: [1, 3] },
      { itemId: 'gnoll_tooth', chance: 0.6, quantity: [1, 3] },
      { itemId: 'copper_coin', chance: 0.8, quantity: [4, 12] },
      { itemId: 'silver_coin', chance: 0.15, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'The gnoll responsible for Blackburrow Stout, a brew famous (or infamous) across Norrath.',
  },

  gnoll_commander_bb: {
    id: 'gnoll_commander_bb',
    name: 'Gnoll Commander',
    level: 10,
    hp: 170,
    atk: 19,
    ac: 14,
    xp: 9000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    enrages: true,
    lootTable: [
      { itemId: 'spiked_collar', chance: 1.0, quantity: [1, 1] },
      { itemId: 'gnoll_fang', chance: 1.0, quantity: [3, 6] },
      { itemId: 'silver_coin', chance: 1.0, quantity: [5, 15] },
      { itemId: 'gold_coin', chance: 0.5, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'Lord of Blackburrow. Ancient, battle-scarred, and utterly ruthless. Few who seek him out return.',
  },

  master_brewer: {
    id: 'master_brewer',
    name: 'Master Brewer',
    level: 11,
    hp: 190,
    atk: 22,
    ac: 16,
    xp: 10000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    enrages: true,
    lootTable: [
      { itemId: 'blackburrow_stout', chance: 1.0, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.9, quantity: [5, 15] },
      { itemId: 'silver_coin', chance: 0.25, quantity: [1, 4] },
    ],
    statusEffects: [],
    description: 'The gnoll responsible for the famous (and potent) Blackburrow Stout. Surprisingly dangerous when cornered.',
  },

  // ─── EVERFROST PEAKS ENEMIES ───────────────────────────────────────────────

  frost_goblin: {
    id: 'frost_goblin',
    name: 'Frost Goblin',
    level: 10,
    hp: 90,
    atk: 14,
    ac: 10,
    xp: 650,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'frost_goblin_shiv', chance: 0.20, quantity: [1, 1] },
      { itemId: 'frost_goblin_cap', chance: 0.15, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.80, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.25, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A blue-skinned goblin shivering with unnatural cold energy.',
  },

  ice_wolf: {
    id: 'ice_wolf',
    name: 'Ice Wolf',
    level: 11,
    hp: 110,
    atk: 16,
    ac: 8,
    xp: 750,
    type: 'animal',
    isRare: false,
    isUndead: false,
    statusProcs: [
      { chance: 0.15, type: 'cold', damage: 5, duration: 9000 },
    ],
    callsForHelp: { chance: 0.50, addIds: ['ice_wolf'] },
    lootTable: [
      { itemId: 'ice_wolf_claw', chance: 0.25, quantity: [1, 1] },
      { itemId: 'ice_wolf_pelt', chance: 0.20, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.60, quantity: [1, 5] },
    ],
    statusEffects: [],
    description: 'A massive white wolf with ice crystals in its fur.',
  },

  snow_skeleton: {
    id: 'snow_skeleton',
    name: 'Snow Skeleton',
    level: 12,
    hp: 100,
    atk: 15,
    ac: 12,
    xp: 800,
    type: 'undead',
    isRare: false,
    isUndead: true,
    lootTable: [
      { itemId: 'frozen_bone_club', chance: 0.20, quantity: [1, 1] },
      { itemId: 'bone_chips', chance: 0.60, quantity: [1, 3] },
      { itemId: 'copper_coin', chance: 0.50, quantity: [1, 4] },
      { itemId: 'silver_coin', chance: 0.10, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'The animated bones of a long-dead adventurer, preserved by the cold.',
  },

  frozen_zombie: {
    id: 'frozen_zombie',
    name: 'Frozen Zombie',
    level: 13,
    hp: 130,
    atk: 18,
    ac: 11,
    xp: 900,
    type: 'undead',
    isRare: false,
    isUndead: true,
    statusProcs: [
      { chance: 0.20, type: 'disease', damage: 6, duration: 12000 },
    ],
    enrages: true,
    lootTable: [
      { itemId: 'frozen_bone_pauldrons', chance: 0.15, quantity: [1, 1] },
      { itemId: 'mammoth_hide_boots', chance: 0.10, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.70, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.15, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'A frozen corpse reanimated by dark magic. Slow but relentless.',
  },

  everfrost_gnoll: {
    id: 'everfrost_gnoll',
    name: 'Everfrost Gnoll',
    level: 12,
    hp: 105,
    atk: 17,
    ac: 10,
    xp: 820,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    callsForHelp: { chance: 0.55, addIds: ['everfrost_gnoll', 'frost_goblin'] },
    lootTable: [
      { itemId: 'everfrost_spear', chance: 0.10, quantity: [1, 1] },
      { itemId: 'frost_goblin_shiv', chance: 0.15, quantity: [1, 1] },
      { itemId: 'everfrost_ringmail_tunic', chance: 0.08, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.40, quantity: [1, 4] },
      { itemId: 'copper_coin', chance: 0.75, quantity: [3, 10] },
    ],
    statusEffects: [],
    description: 'A gnoll that has migrated to Everfrost, toughened by the cold.',
  },

  ice_giant_scout: {
    id: 'ice_giant_scout',
    name: 'Ice Giant Scout',
    level: 18,
    hp: 280,
    atk: 28,
    ac: 18,
    xp: 5500,
    type: 'giant',
    isRare: true,
    isUndead: false,
    aoeAttack: true,
    enrages: true,
    lootTable: [
      { itemId: 'ice_giant_maul', chance: 0.30, quantity: [1, 1] },
      { itemId: 'ice_giant_bracer', chance: 0.25, quantity: [1, 1] },
      { itemId: 'everfrost_amulet', chance: 0.15, quantity: [1, 1] },
      { itemId: 'gold_coin', chance: 0.80, quantity: [2, 6] },
      { itemId: 'silver_coin', chance: 1.00, quantity: [5, 15] },
    ],
    statusEffects: [],
    description: 'A towering frost giant patrolling the peaks. His footsteps crack the ice.',
  },

  a_wooly_mammoth: {
    id: 'a_wooly_mammoth',
    name: 'a Wooly Mammoth',
    level: 15,
    hp: 220,
    atk: 24,
    ac: 14,
    xp: 3200,
    type: 'animal',
    isRare: true,
    isUndead: false,
    aoeAttack: true,
    enrages: true,
    lootTable: [
      { itemId: 'mammoth_ivory_staff', chance: 0.20, quantity: [1, 1] },
      { itemId: 'mammoth_hide_boots', chance: 0.30, quantity: [1, 1] },
      { itemId: 'everfrost_amulet', chance: 0.10, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.80, quantity: [3, 10] },
    ],
    statusEffects: [],
    description: 'An ancient mammoth with tusks like battering rams.',
  },

  permafrost_spectre: {
    id: 'permafrost_spectre',
    name: 'Permafrost Spectre',
    level: 17,
    hp: 190,
    atk: 22,
    ac: 16,
    xp: 4800,
    type: 'undead',
    isRare: true,
    isUndead: true,
    magicResist: 25,
    statusProcs: [
      { chance: 0.30, type: 'cold', damage: 10, duration: 15000 },
    ],
    aoeAttack: false,
    lootTable: [
      { itemId: 'spectral_blade', chance: 0.25, quantity: [1, 1] },
      { itemId: 'spectre_shroud', chance: 0.20, quantity: [1, 1] },
      { itemId: 'frost_crystal_ring', chance: 0.30, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.90, quantity: [4, 12] },
      { itemId: 'gold_coin', chance: 0.30, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A ghostly figure trapped in ice for centuries. Its wail chills the soul.',
  },

  // ── West Karana (levels 20-30) ─────────────────────────────────────────────

  karana_bandit: {
    id: 'karana_bandit',
    name: 'Karana Bandit',
    level: 20,
    hp: 80,
    atk: 25,
    ac: 16,
    xp: 20000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'silver_coin', chance: 0.80, quantity: [1, 5] },
      { itemId: 'gold_coin', chance: 0.20, quantity: [1, 2] },
      { itemId: 'bandit_shortsword', chance: 0.40, quantity: [1, 1] },
      { itemId: 'cloth_scraps', chance: 0.60, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'A hardened criminal preying on travelers crossing the Karana plains.',
  },

  karana_raider: {
    id: 'karana_raider',
    name: 'Karana Raider',
    level: 22,
    hp: 110,
    atk: 29,
    ac: 18,
    xp: 22000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'silver_coin', chance: 0.80, quantity: [2, 6] },
      { itemId: 'gold_coin', chance: 0.25, quantity: [1, 2] },
      { itemId: 'raider_axe', chance: 0.35, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'A brutal raider who ambushes trade caravans on the open plains.',
  },

  giant_wolf: {
    id: 'giant_wolf',
    name: 'Giant Wolf',
    level: 21,
    hp: 95,
    atk: 27,
    ac: 17,
    xp: 21000,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'giant_wolf_pelt', chance: 0.50, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.70, quantity: [1, 4] },
    ],
    statusEffects: [],
    description: 'A massive wolf, larger than any natural specimen. Its howl carries for miles.',
  },

  plains_griffon: {
    id: 'plains_griffon',
    name: 'Plains Griffon',
    level: 24,
    hp: 155,
    atk: 33,
    ac: 20,
    xp: 48000,
    type: 'animal',
    isRare: true,
    isUndead: false,
    aoeAttack: true,
    lootTable: [
      { itemId: 'griffon_feather', chance: 0.60, quantity: [1, 1] },
      { itemId: 'griffon_talon', chance: 0.40, quantity: [1, 1] },
      { itemId: 'gold_coin', chance: 0.70, quantity: [1, 4] },
      { itemId: 'silver_coin', chance: 1.00, quantity: [3, 10] },
    ],
    statusEffects: [],
    description: 'A magnificent griffon that hunts the Karana plains. Dangerous to all who approach its territory.',
  },

  karana_gnoll_warrior: {
    id: 'karana_gnoll_warrior',
    name: 'Karana Gnoll Warrior',
    level: 26,
    hp: 185,
    atk: 37,
    ac: 22,
    xp: 26000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    callsForHelp: true,
    lootTable: [
      { itemId: 'gnoll_war_club', chance: 0.35, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.80, quantity: [2, 8] },
      { itemId: 'copper_coin', chance: 1.00, quantity: [5, 15] },
    ],
    statusEffects: [],
    description: 'A gnoll warrior from the plains pack. Known to call allies when threatened.',
  },

  plains_cyclops: {
    id: 'plains_cyclops',
    name: 'Plains Cyclops',
    level: 28,
    hp: 235,
    atk: 41,
    ac: 24,
    xp: 56000,
    type: 'giant',
    isRare: true,
    isUndead: false,
    aoeAttack: true,
    enrages: true,
    lootTable: [
      { itemId: 'cyclops_eye', chance: 0.50, quantity: [1, 1] },
      { itemId: 'cyclops_hide_belt', chance: 0.20, quantity: [1, 1] },
      { itemId: 'gold_coin', chance: 0.80, quantity: [2, 6] },
      { itemId: 'silver_coin', chance: 1.00, quantity: [5, 15] },
    ],
    statusEffects: [],
    description: 'A massive one-eyed giant wandering the Karana plains. Its single eye can spot prey from great distances.',
  },

  dust_goblin: {
    id: 'dust_goblin',
    name: 'Dust Goblin',
    level: 23,
    hp: 125,
    atk: 31,
    ac: 19,
    xp: 23000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'dust_goblin_cap', chance: 0.30, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.75, quantity: [1, 5] },
      { itemId: 'copper_coin', chance: 1.00, quantity: [3, 10] },
    ],
    statusEffects: [],
    description: 'A small but vicious goblin covered in dust from the dry plains. Loves to steal and ambush lone travelers.',
  },

  // ── Highpass Hold (levels 25-35) ───────────────────────────────────────────

  highpass_guard: {
    id: 'highpass_guard',
    name: 'Highpass Guard',
    level: 25,
    hp: 170,
    atk: 35,
    ac: 21,
    xp: 25000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'guard_short_sword', chance: 0.35, quantity: [1, 1] },
      { itemId: 'guard_chainmail', chance: 0.25, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.80, quantity: [2, 6] },
      { itemId: 'gold_coin', chance: 0.20, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'A hardened soldier of the Highpass garrison. Corrupt and dangerous.',
  },

  pass_bandit: {
    id: 'pass_bandit',
    name: 'Pass Bandit',
    level: 27,
    hp: 200,
    atk: 39,
    ac: 23,
    xp: 27000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'pass_bandit_blade', chance: 0.40, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.80, quantity: [2, 8] },
      { itemId: 'gold_coin', chance: 0.25, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A ruthless bandit who preys on travelers using the mountain pass.',
  },

  gnoll_war_chief: {
    id: 'gnoll_war_chief',
    name: 'Gnoll War Chief',
    level: 30,
    hp: 260,
    atk: 45,
    ac: 26,
    xp: 60000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    callsForHelp: true,
    lootTable: [
      { itemId: 'war_chief_axe', chance: 0.30, quantity: [1, 1] },
      { itemId: 'gnoll_war_totem', chance: 0.25, quantity: [1, 1] },
      { itemId: 'gold_coin', chance: 0.80, quantity: [2, 6] },
      { itemId: 'silver_coin', chance: 1.00, quantity: [5, 15] },
    ],
    statusEffects: [],
    description: 'The brutal leader of the Highpass gnoll war parties. Rallies his warriors with a terrifying battle cry.',
  },

  mountain_bear: {
    id: 'mountain_bear',
    name: 'Mountain Bear',
    level: 28,
    hp: 220,
    atk: 41,
    ac: 24,
    xp: 28000,
    type: 'animal',
    isRare: false,
    isUndead: false,
    enrages: true,
    lootTable: [
      { itemId: 'thick_bear_pelt', chance: 0.50, quantity: [1, 1] },
      { itemId: 'bear_claw', chance: 0.40, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.70, quantity: [2, 7] },
    ],
    statusEffects: [],
    description: 'A massive bear that makes its den in the mountain pass caves. Its claws can rend steel.',
  },

  highpass_skeleton: {
    id: 'highpass_skeleton',
    name: 'Highpass Skeleton',
    level: 29,
    hp: 230,
    atk: 43,
    ac: 25,
    xp: 29000,
    type: 'undead',
    isRare: false,
    isUndead: true,
    lootTable: [
      { itemId: 'bone_chips', chance: 0.60, quantity: [1, 3] },
      { itemId: 'old_sword', chance: 0.30, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.60, quantity: [2, 6] },
    ],
    statusEffects: [],
    description: 'The animated remains of a soldier who fell in the pass long ago. Still guards its post.',
  },

  rock_troll: {
    id: 'rock_troll',
    name: 'Rock Troll',
    level: 33,
    hp: 320,
    atk: 51,
    ac: 29,
    xp: 66000,
    type: 'giant',
    isRare: true,
    isUndead: false,
    aoeAttack: true,
    lootTable: [
      { itemId: 'troll_hide_tunic', chance: 0.20, quantity: [1, 1] },
      { itemId: 'troll_smash_club', chance: 0.25, quantity: [1, 1] },
      { itemId: 'gold_coin', chance: 0.80, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 1.00, quantity: [5, 20] },
    ],
    statusEffects: [],
    description: 'A hulking troll that lurks among the boulders of the pass, ambushing travelers.',
  },

  // ── Kithicor Forest (levels 30-42) ────────────────────────────────────────

  kithicor_skeleton: {
    id: 'kithicor_skeleton',
    name: 'Kithicor Skeleton',
    level: 30,
    hp: 245,
    atk: 45,
    ac: 26,
    xp: 30000,
    type: 'undead',
    isRare: false,
    isUndead: true,
    lootTable: [
      { itemId: 'bone_chips', chance: 0.70, quantity: [1, 3] },
      { itemId: 'spirit_dust', chance: 0.40, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.60, quantity: [2, 6] },
    ],
    statusEffects: [],
    description: 'The restless bones of a soldier killed in the Battle of Bloody Kithicor.',
  },

  kithicor_zombie: {
    id: 'kithicor_zombie',
    name: 'Kithicor Zombie',
    level: 32,
    hp: 275,
    atk: 49,
    ac: 28,
    xp: 32000,
    type: 'undead',
    isRare: false,
    isUndead: true,
    statusProcs: [
      { chance: 0.25, type: 'disease', damage: 8, duration: 20000 },
    ],
    lootTable: [
      { itemId: 'rotting_flesh', chance: 0.50, quantity: [1, 2] },
      { itemId: 'silver_coin', chance: 0.60, quantity: [2, 8] },
      { itemId: 'copper_coin', chance: 0.80, quantity: [5, 15] },
    ],
    statusEffects: [],
    description: 'A shambling undead soldier, still wearing the rotting remnants of its battle armor.',
  },

  kithicor_warrior_spirit: {
    id: 'kithicor_warrior_spirit',
    name: 'Kithicor Warrior Spirit',
    level: 35,
    hp: 320,
    atk: 55,
    ac: 30,
    xp: 35000,
    type: 'undead',
    isRare: false,
    isUndead: true,
    magicResist: 15,
    lootTable: [
      { itemId: 'spirit_sword', chance: 0.25, quantity: [1, 1] },
      { itemId: 'spirit_essence', chance: 0.30, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.70, quantity: [3, 10] },
      { itemId: 'gold_coin', chance: 0.25, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'The tortured spirit of a warrior slain in the forest battle, bound here by dark magic.',
  },

  corrupted_treant: {
    id: 'corrupted_treant',
    name: 'Corrupted Treant',
    level: 36,
    hp: 335,
    atk: 57,
    ac: 31,
    xp: 36000,
    type: 'plant',
    isRare: false,
    isUndead: false,
    aoeAttack: true,
    lootTable: [
      { itemId: 'treant_bark', chance: 0.60, quantity: [1, 2] },
      { itemId: 'treant_heartwood', chance: 0.15, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.50, quantity: [2, 8] },
    ],
    statusEffects: [],
    description: 'An ancient tree spirit twisted by the dark magic that permeates Kithicor. Its roots can crush stone.',
  },

  kithicor_dark_elf: {
    id: 'kithicor_dark_elf',
    name: 'Kithicor Dark Elf',
    level: 38,
    hp: 365,
    atk: 61,
    ac: 33,
    xp: 38000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'dark_elf_blade', chance: 0.30, quantity: [1, 1] },
      { itemId: 'dark_elf_cloak', chance: 0.25, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.80, quantity: [3, 10] },
      { itemId: 'gold_coin', chance: 0.30, quantity: [1, 4] },
    ],
    statusEffects: [],
    description: 'A Teir\'Dal scout using the haunted forest as cover for dark operations.',
  },

  general_kill_anaz: {
    id: 'general_kill_anaz',
    name: 'General Kill-Anaz',
    level: 42,
    hp: 540,
    atk: 69,
    ac: 38,
    xp: 84000,
    type: 'undead',
    isRare: true,
    isUndead: true,
    aoeAttack: true,
    enrages: true,
    magicResist: 30,
    lootTable: [
      { itemId: 'kill_anaz_greatsword', chance: 0.25, quantity: [1, 1] },
      { itemId: 'spectral_plate_chest', chance: 0.20, quantity: [1, 1] },
      { itemId: 'gold_coin', chance: 0.90, quantity: [3, 10] },
      { itemId: 'silver_coin', chance: 1.00, quantity: [10, 25] },
    ],
    statusEffects: [],
    description: 'The spectral commander of the undead army. General Kill-Anaz fell in battle long ago but refuses to rest.',
  },

  // ── Commonlands (levels 38-50) ─────────────────────────────────────────────

  orc_warrior: {
    id: 'orc_warrior',
    name: 'Orc Warrior',
    level: 38,
    hp: 365,
    atk: 61,
    ac: 33,
    xp: 38000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    callsForHelp: true,
    lootTable: [
      { itemId: 'orc_war_blade', chance: 0.35, quantity: [1, 1] },
      { itemId: 'orc_hide_armor', chance: 0.30, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.80, quantity: [3, 10] },
      { itemId: 'gold_coin', chance: 0.25, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A brutal Crushbone orc warrior patrolling the Commonlands roads.',
  },

  orc_shaman: {
    id: 'orc_shaman',
    name: 'Orc Shaman',
    level: 40,
    hp: 395,
    atk: 65,
    ac: 35,
    xp: 40000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    statusProcs: [
      { chance: 0.30, type: 'disease', damage: 12, duration: 25000 },
    ],
    lootTable: [
      { itemId: 'orc_shaman_staff', chance: 0.30, quantity: [1, 1] },
      { itemId: 'orc_shaman_beads', chance: 0.25, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.75, quantity: [3, 10] },
      { itemId: 'gold_coin', chance: 0.25, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'An orc shaman calling upon dark spirits to curse enemies with disease.',
  },

  orc_captain: {
    id: 'orc_captain',
    name: 'Orc Captain',
    level: 43,
    hp: 440,
    atk: 71,
    ac: 38,
    xp: 43000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    callsForHelp: true,
    aoeAttack: true,
    lootTable: [
      { itemId: 'captain_sword', chance: 0.25, quantity: [1, 1] },
      { itemId: 'captain_shield', chance: 0.20, quantity: [1, 1] },
      { itemId: 'gold_coin', chance: 0.70, quantity: [2, 6] },
      { itemId: 'silver_coin', chance: 1.00, quantity: [5, 15] },
    ],
    statusEffects: [],
    description: 'A veteran orc officer commanding Crushbone forces in the Commonlands.',
  },

  commonlands_lion: {
    id: 'commonlands_lion',
    name: 'Commonlands Lion',
    level: 41,
    hp: 410,
    atk: 67,
    ac: 36,
    xp: 41000,
    type: 'animal',
    isRare: false,
    isUndead: false,
    enrages: true,
    lootTable: [
      { itemId: 'lion_pelt', chance: 0.55, quantity: [1, 1] },
      { itemId: 'lion_claw', chance: 0.45, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.65, quantity: [2, 8] },
    ],
    statusEffects: [],
    description: 'A great lion of the Commonlands plains, fiercely territorial and lethal.',
  },

  dark_elf_ranger: {
    id: 'dark_elf_ranger',
    name: 'Dark Elf Ranger',
    level: 44,
    hp: 455,
    atk: 73,
    ac: 39,
    xp: 44000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'dark_elf_longbow', chance: 0.30, quantity: [1, 1] },
      { itemId: 'dark_elf_quiver', chance: 0.40, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.80, quantity: [3, 10] },
      { itemId: 'gold_coin', chance: 0.30, quantity: [1, 4] },
    ],
    statusEffects: [],
    description: 'A Teir\'Dal ranger skilled in ambush tactics and long-range strikes.',
  },

  crushbone_warlord: {
    id: 'crushbone_warlord',
    name: 'Crushbone Warlord',
    level: 48,
    hp: 620,
    atk: 81,
    ac: 44,
    xp: 96000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    aoeAttack: true,
    enrages: true,
    lootTable: [
      { itemId: 'warlord_axe', chance: 0.20, quantity: [1, 1] },
      { itemId: 'crushbone_shoulderplates', chance: 0.18, quantity: [1, 1] },
      { itemId: 'gold_coin', chance: 0.90, quantity: [4, 12] },
      { itemId: 'silver_coin', chance: 1.00, quantity: [10, 30] },
    ],
    statusEffects: [],
    description: 'The fearsome warlord of the Crushbone Empire. His war cries rally orcs throughout the Commonlands.',
  },

  plague_spectre: {
    id: 'plague_spectre',
    name: 'Plague Spectre',
    level: 50,
    hp: 650,
    atk: 85,
    ac: 46,
    xp: 100000,
    type: 'undead',
    isRare: true,
    isUndead: true,
    aoeAttack: true,
    magicResist: 35,
    statusProcs: [
      { chance: 0.35, type: 'disease', damage: 15, duration: 30000 },
    ],
    lootTable: [
      { itemId: 'plague_shroud', chance: 0.22, quantity: [1, 1] },
      { itemId: 'spectre_essence_ring', chance: 0.18, quantity: [1, 1] },
      { itemId: 'gold_coin', chance: 0.90, quantity: [5, 15] },
      { itemId: 'silver_coin', chance: 1.00, quantity: [15, 35] },
    ],
    statusEffects: [],
    description: 'A specter wreathed in plague. Its mere presence causes disease to spread.',
  },
};

/**
 * Retrieve a single enemy template by its ID.
 *
 * @param {string} id - The snake_case enemy ID to look up.
 * @returns {object|null} The enemy definition object, or null if not found.
 */
function getEnemy(id) {
  return ENEMIES[id] || null;
}

/**
 * Return all enemy templates whose level falls within an inclusive range.
 *
 * @param {number} min - Minimum enemy level (inclusive).
 * @param {number} max - Maximum enemy level (inclusive).
 * @returns {Array<object>} Array of enemy definition objects matching the range.
 */
function getEnemiesByLevelRange(min, max) {
  return Object.values(ENEMIES).filter(e => e.level >= min && e.level <= max);
}

/**
 * Perform a loot roll for a defeated enemy, applying per-item drop chances.
 *
 * Iterates the enemy's lootTable and, for each entry, rolls against its
 * drop chance. Successful rolls yield a random quantity within the entry's
 * [min, max] range.
 *
 * @param {object} enemy - An enemy definition object (must have a lootTable).
 * @returns {Array<{itemId: string, quantity: number}>} Array of dropped item stacks.
 */
function rollLoot(enemy) {
  const results = [];
  for (const entry of enemy.lootTable) {
    if (Math.random() < entry.chance) {
      const [minQty, maxQty] = entry.quantity;
      const quantity = Math.floor(Math.random() * (maxQty - minQty + 1)) + minQty;
      results.push({ itemId: entry.itemId, quantity });
    }
  }
  return results;
}

if (typeof module !== 'undefined') module.exports = { ENEMIES, getEnemy, getEnemiesByLevelRange, rollLoot };
