const ENEMIES = {
  mangy_rat: {
    id: 'mangy_rat',
    name: 'Mangy Rat',
    level: 1,
    hp: 15,
    atk: 2,
    ac: 1,
    xp: 500,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'rat_pelt', chance: 0.5, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.5, quantity: [1, 4] },
      { itemId: 'silver_coin', chance: 0.05, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'A flea-ridden rat barely worth drawing your weapon for.',
  },

  giant_rat: {
    id: 'giant_rat',
    name: 'Giant Rat',
    level: 2,
    hp: 25,
    atk: 3,
    ac: 3,
    xp: 800,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'rat_pelt', chance: 0.5, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.6, quantity: [1, 5] },
      { itemId: 'silver_coin', chance: 0.07, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Larger than its mangy cousin, this rat has learned to survive by being aggressive.',
  },

  large_rat: {
    id: 'large_rat',
    name: 'Large Rat',
    level: 3,
    hp: 35,
    atk: 5,
    ac: 4,
    xp: 1200,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'rat_pelt', chance: 0.5, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [1, 6] },
      { itemId: 'silver_coin', chance: 0.08, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'An unnaturally large rodent with yellowed teeth and a vicious temperament.',
  },

  fire_beetle: {
    id: 'fire_beetle',
    name: 'Fire Beetle',
    level: 3,
    hp: 30,
    atk: 5,
    ac: 5,
    xp: 1200,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'fire_beetle_eye', chance: 0.7, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.55, quantity: [1, 5] },
      { itemId: 'silver_coin', chance: 0.07, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Its abdomen glows with a bioluminescent orange light, prized by alchemists.',
  },

  snake: {
    id: 'snake',
    name: 'Snake',
    level: 2,
    hp: 20,
    atk: 4,
    ac: 2,
    xp: 800,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'snake_scale', chance: 0.6, quantity: [1, 3] },
      { itemId: 'copper_coin', chance: 0.5, quantity: [1, 4] },
      { itemId: 'silver_coin', chance: 0.06, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'A common hill snake that blends expertly into the tall grass.',
  },

  king_snake: {
    id: 'king_snake',
    name: 'King Snake',
    level: 5,
    hp: 65,
    atk: 9,
    ac: 8,
    xp: 2500,
    type: 'animal',
    isRare: true,
    isUndead: false,
    lootTable: [
      { itemId: 'snake_scale', chance: 0.6, quantity: [2, 5] },
      { itemId: 'copper_coin', chance: 0.7, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.15, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A massive serpent that lords over the lesser snakes of the hills. Rarely seen.',
  },

  bat: {
    id: 'bat',
    name: 'Bat',
    level: 2,
    hp: 18,
    atk: 3,
    ac: 2,
    xp: 700,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'bat_wing', chance: 0.6, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.5, quantity: [1, 3] },
      { itemId: 'silver_coin', chance: 0.05, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'A squealing cave bat drawn out into the hills at dusk.',
  },

  giant_bat: {
    id: 'giant_bat',
    name: 'Giant Bat',
    level: 5,
    hp: 60,
    atk: 8,
    ac: 6,
    xp: 2200,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'bat_wing', chance: 0.8, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [2, 7] },
      { itemId: 'silver_coin', chance: 0.12, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'With a wingspan that blocks out the moon, this beast is a terror of the night sky.',
  },

  gnoll_pup: {
    id: 'gnoll_pup',
    name: 'Gnoll Pup',
    level: 3,
    hp: 40,
    atk: 6,
    ac: 5,
    xp: 1500,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_tooth', chance: 0.5, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [1, 6] },
      { itemId: 'silver_coin', chance: 0.08, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Young and reckless, gnoll pups are eager to prove themselves through violence.',
  },

  gnoll: {
    id: 'gnoll',
    name: 'Gnoll',
    level: 5,
    hp: 75,
    atk: 10,
    ac: 8,
    xp: 3000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.4, quantity: [1, 1] },
      { itemId: 'rusty_short_sword', chance: 0.1, quantity: [1, 1] },
      { itemId: 'gnoll_tooth', chance: 0.6, quantity: [1, 3] },
      { itemId: 'copper_coin', chance: 0.75, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.12, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'A full-grown gnoll warrior, hyena-headed and wielding crude weapons with brutal efficiency.',
  },

  gnoll_scout: {
    id: 'gnoll_scout',
    name: 'Gnoll Scout',
    level: 7,
    hp: 100,
    atk: 14,
    ac: 10,
    xp: 4500,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.5, quantity: [1, 2] },
      { itemId: 'gnoll_slayer', chance: 0.05, quantity: [1, 1] },
      { itemId: 'tarnished_axe', chance: 0.1, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.78, quantity: [3, 10] },
      { itemId: 'silver_coin', chance: 0.15, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A quick and cunning gnoll that ranges far ahead of the pack to ambush unwary travelers.',
  },

  gnoll_watcher: {
    id: 'gnoll_watcher',
    name: 'Gnoll Watcher',
    level: 8,
    hp: 120,
    atk: 16,
    ac: 12,
    xp: 5500,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.55, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.78, quantity: [3, 12] },
      { itemId: 'silver_coin', chance: 0.17, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'Stationed at the perimeter of the gnoll camp, the watcher calls out with a piercing howl when intruders approach.',
  },

  gnoll_hunter: {
    id: 'gnoll_hunter',
    name: 'Gnoll Hunter',
    level: 9,
    hp: 145,
    atk: 18,
    ac: 14,
    xp: 7000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.6, quantity: [1, 3] },
      { itemId: 'tarnished_axe', chance: 0.15, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.8, quantity: [4, 14] },
      { itemId: 'silver_coin', chance: 0.2, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'An elite gnoll tracker who moves silently despite its bulk, trapping prey with practiced cruelty.',
  },

  gray_wolf: {
    id: 'gray_wolf',
    name: 'Gray Wolf',
    level: 4,
    hp: 55,
    atk: 8,
    ac: 6,
    xp: 2000,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'wolf_pelt', chance: 0.65, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.6, quantity: [1, 6] },
      { itemId: 'silver_coin', chance: 0.09, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'A lean pack hunter with pale gray fur and intelligent amber eyes.',
  },

  rabid_wolf: {
    id: 'rabid_wolf',
    name: 'Rabid Wolf',
    level: 6,
    hp: 85,
    atk: 12,
    ac: 8,
    xp: 3500,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'wolf_pelt', chance: 0.75, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [2, 7] },
      { itemId: 'silver_coin', chance: 0.11, quantity: [1, 2] },
    ],
    statusEffects: [
      { type: 'poison', chance: 0.2, duration: 10000, damage: 3 },
    ],
    description: 'Foam flecks its muzzle and its eyes burn with mindless fury — approach only if you have no other choice.',
  },

  brown_bear: {
    id: 'brown_bear',
    name: 'Brown Bear',
    level: 6,
    hp: 90,
    atk: 11,
    ac: 9,
    xp: 3800,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'bear_pelt', chance: 0.6, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [1, 7] },
      { itemId: 'silver_coin', chance: 0.11, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'A territorial brown bear that will charge anything that wanders too close to its den.',
  },

  grizzly_bear: {
    id: 'grizzly_bear',
    name: 'Grizzly Bear',
    level: 8,
    hp: 130,
    atk: 17,
    ac: 13,
    xp: 6000,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'bear_pelt', chance: 0.75, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.7, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.15, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'Massive and temperamental, the grizzly bear is the apex predator of the Qeynos Hills.',
  },

  decaying_skeleton: {
    id: 'decaying_skeleton',
    name: 'Decaying Skeleton',
    level: 5,
    hp: 70,
    atk: 9,
    ac: 7,
    xp: 2800,
    type: 'undead',
    isRare: false,
    isUndead: true,
    lootTable: [
      { itemId: 'bone_chips', chance: 0.8, quantity: [1, 3] },
      { itemId: 'cracked_staff', chance: 0.05, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.6, quantity: [1, 5] },
      { itemId: 'silver_coin', chance: 0.08, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Animated by dark magic, this crumbling skeleton rattles and scrapes as it shambles toward the living.',
  },

  putrid_skeleton: {
    id: 'putrid_skeleton',
    name: 'Putrid Skeleton',
    level: 7,
    hp: 95,
    atk: 13,
    ac: 10,
    xp: 4200,
    type: 'undead',
    isRare: false,
    isUndead: true,
    lootTable: [
      { itemId: 'bone_chips', chance: 0.9, quantity: [1, 4] },
      { itemId: 'copper_coin', chance: 0.65, quantity: [1, 6] },
      { itemId: 'silver_coin', chance: 0.1, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'Older and more powerful than a decaying skeleton, its bones are stained black with necrotic energy.',
  },

  dread_corpse: {
    id: 'dread_corpse',
    name: 'Dread Corpse',
    level: 8,
    hp: 115,
    atk: 15,
    ac: 11,
    xp: 5200,
    type: 'undead',
    isRare: false,
    isUndead: true,
    lootTable: [
      { itemId: 'bone_chips', chance: 0.85, quantity: [2, 5] },
      { itemId: 'copper_coin', chance: 0.68, quantity: [2, 7] },
      { itemId: 'silver_coin', chance: 0.12, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'A bloated, shambling horror whose very presence dims the light and chills the blood.',
  },

  will_o_wisp: {
    id: 'will_o_wisp',
    name: "Will O' Wisp",
    level: 10,
    hp: 160,
    atk: 20,
    ac: 15,
    xp: 8000,
    type: 'magical',
    isRare: false,
    isUndead: false,
    magicResist: 50,
    lootTable: [
      { itemId: 'copper_coin', chance: 0.7, quantity: [3, 8] },
      { itemId: 'silver_coin', chance: 0.2, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A drifting orb of cold, eldritch light that lures travelers off the path to their doom. Highly resistant to magic.',
  },

  bandit: {
    id: 'bandit',
    name: 'Bandit',
    level: 6,
    hp: 80,
    atk: 12,
    ac: 9,
    xp: 3300,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'copper_coin', chance: 0.9, quantity: [3, 15] },
      { itemId: 'silver_coin', chance: 0.3, quantity: [1, 5] },
      { itemId: 'rusty_short_sword', chance: 0.15, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'A desperate cutthroat who preys on travelers along the roads outside Qeynos.',
  },

  hadden: {
    id: 'hadden',
    name: 'Hadden',
    level: 12,
    hp: 250,
    atk: 25,
    ac: 20,
    xp: 15000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    lootTable: [
      { itemId: 'fishbone_earring', chance: 1.0, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 1.0, quantity: [5, 20] },
    ],
    statusEffects: [],
    description: 'A wandering hermit whose strange earring is said to carry magical properties. He does not part with it willingly.',
  },

  varsoon_the_undying: {
    id: 'varsoon_the_undying',
    name: 'Varsoon the Undying',
    level: 12,
    hp: 280,
    atk: 28,
    ac: 18,
    xp: 17500,
    type: 'undead',
    isRare: true,
    isUndead: true,
    lootTable: [
      { itemId: 'glowing_black_stone', chance: 1.0, quantity: [1, 1] },
      { itemId: 'bone_chips', chance: 1.0, quantity: [5, 10] },
      { itemId: 'silver_coin', chance: 0.8, quantity: [3, 10] },
    ],
    statusEffects: [],
    description: 'An ancient necromancer who cheated death one too many times. Now he IS death, wandering the hills in a decayed body held together by sheer hatred.',
  },

  scrawny_gnoll: {
    id: 'scrawny_gnoll',
    name: 'Scrawny Gnoll',
    level: 4,
    hp: 50,
    atk: 7,
    ac: 6,
    xp: 1800,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_tooth', chance: 0.5, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.7, quantity: [1, 8] },
      { itemId: 'silver_coin', chance: 0.09, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'A lean, mangy gnoll barely past puphood. Dangerous in numbers.',
  },

  burly_gnoll: {
    id: 'burly_gnoll',
    name: 'Burly Gnoll',
    level: 7,
    hp: 105,
    atk: 15,
    ac: 11,
    xp: 5000,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.55, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.8, quantity: [3, 12] },
      { itemId: 'silver_coin', chance: 0.14, quantity: [1, 2] },
    ],
    statusEffects: [],
    description: 'Thick-necked and barrel-chested, this gnoll hits harder than it looks.',
  },

  gnoll_guard: {
    id: 'gnoll_guard',
    name: 'Gnoll Guard',
    level: 9,
    hp: 140,
    atk: 19,
    ac: 15,
    xp: 7500,
    type: 'humanoid',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.65, quantity: [1, 3] },
      { itemId: 'gnoll_hide_lariat', chance: 0.05, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.82, quantity: [4, 16] },
      { itemId: 'silver_coin', chance: 0.22, quantity: [1, 4] },
    ],
    statusEffects: [],
    description: 'Stationed at key tunnels deep in Blackburrow. Disciplined and aggressive.',
  },

  gnoll_shaman: {
    id: 'gnoll_shaman',
    name: 'Gnoll Shaman',
    level: 10,
    hp: 155,
    atk: 18,
    ac: 13,
    xp: 8500,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.6, quantity: [1, 2] },
      { itemId: 'runed_totem_staff', chance: 0.08, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.8, quantity: [4, 14] },
      { itemId: 'silver_coin', chance: 0.2, quantity: [1, 3] },
    ],
    statusEffects: [
      { type: 'poison', chance: 0.15, duration: 12000, damage: 4 },
    ],
    description: 'A fetish-adorned gnoll witch doctor. Its bone rattles herald a hex.',
  },

  gnoll_commander: {
    id: 'gnoll_commander',
    name: 'Gnoll Commander',
    level: 12,
    hp: 210,
    atk: 24,
    ac: 18,
    xp: 12000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.7, quantity: [2, 4] },
      { itemId: 'spiked_collar', chance: 0.12, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.85, quantity: [5, 20] },
      { itemId: 'silver_coin', chance: 0.3, quantity: [2, 5] },
      { itemId: 'gold_coin', chance: 0.08, quantity: [1, 1] },
    ],
    statusEffects: [],
    description: 'Commands the gnoll forces in the deep tunnels with a bark that makes even burly gnolls flinch.',
  },

  gnoll_high_shaman: {
    id: 'gnoll_high_shaman',
    name: 'Gnoll High Shaman',
    level: 14,
    hp: 260,
    atk: 27,
    ac: 20,
    xp: 16000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    magicResist: 25,
    lootTable: [
      { itemId: 'gnoll_fang', chance: 0.75, quantity: [2, 5] },
      { itemId: 'runed_totem_staff', chance: 0.15, quantity: [1, 1] },
      { itemId: 'silver_coin', chance: 0.5, quantity: [3, 8] },
      { itemId: 'gold_coin', chance: 0.15, quantity: [1, 2] },
    ],
    statusEffects: [
      { type: 'poison', chance: 0.25, duration: 15000, damage: 6 },
    ],
    description: 'The spiritual leader of the Blackburrow pack. Radiates dark power.',
  },

  giant_plague_rat: {
    id: 'giant_plague_rat',
    name: 'Giant Plague Rat',
    level: 5,
    hp: 70,
    atk: 10,
    ac: 7,
    xp: 2600,
    type: 'animal',
    isRare: false,
    isUndead: false,
    lootTable: [
      { itemId: 'rat_pelt', chance: 0.6, quantity: [1, 2] },
      { itemId: 'copper_coin', chance: 0.7, quantity: [2, 8] },
      { itemId: 'silver_coin', chance: 0.08, quantity: [1, 1] },
    ],
    statusEffects: [
      { type: 'poison', chance: 0.3, duration: 10000, damage: 3 },
    ],
    description: 'A bloated, diseased rat infesting the lower tunnels of Blackburrow. Its bite festers.',
  },

  giant_snake_bb: {
    id: 'giant_snake_bb',
    name: 'Giant Snake',
    level: 8,
    hp: 125,
    atk: 16,
    ac: 12,
    xp: 6000,
    type: 'animal',
    isRare: true,
    isUndead: false,
    lootTable: [
      { itemId: 'snake_scale', chance: 0.7, quantity: [2, 5] },
      { itemId: 'giant_snake_fang', chance: 0.6, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.7, quantity: [3, 10] },
      { itemId: 'silver_coin', chance: 0.15, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'A massive constrictor lurking in the flooded lower pit of Blackburrow.',
  },

  lord_elgnub: {
    id: 'lord_elgnub',
    name: 'Lord Elgnub',
    level: 15,
    hp: 320,
    atk: 32,
    ac: 22,
    xp: 22000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    lootTable: [
      { itemId: 'spiked_collar', chance: 1.0, quantity: [1, 1] },
      { itemId: 'gnoll_fang', chance: 1.0, quantity: [3, 6] },
      { itemId: 'silver_coin', chance: 1.0, quantity: [5, 15] },
      { itemId: 'gold_coin', chance: 0.5, quantity: [1, 3] },
    ],
    statusEffects: [],
    description: 'Lord of Blackburrow. Ancient, battle-scarred, and utterly ruthless. Few who seek him out return.',
  },

  master_brewer: {
    id: 'master_brewer',
    name: 'Master Brewer',
    level: 11,
    hp: 190,
    atk: 22,
    ac: 16,
    xp: 10000,
    type: 'humanoid',
    isRare: true,
    isUndead: false,
    lootTable: [
      { itemId: 'blackburrow_stout', chance: 1.0, quantity: [1, 1] },
      { itemId: 'copper_coin', chance: 0.9, quantity: [5, 15] },
      { itemId: 'silver_coin', chance: 0.25, quantity: [1, 4] },
    ],
    statusEffects: [],
    description: 'The gnoll responsible for the famous (and potent) Blackburrow Stout. Surprisingly dangerous when cornered.',
  },
};

function getEnemy(id) {
  return ENEMIES[id] || null;
}

function getEnemiesByLevelRange(min, max) {
  return Object.values(ENEMIES).filter(e => e.level >= min && e.level <= max);
}

function rollLoot(enemy) {
  const results = [];
  for (const entry of enemy.lootTable) {
    if (Math.random() < entry.chance) {
      const [minQty, maxQty] = entry.quantity;
      const quantity = Math.floor(Math.random() * (maxQty - minQty + 1)) + minQty;
      results.push({ itemId: entry.itemId, quantity });
    }
  }
  return results;
}

if (typeof module !== 'undefined') module.exports = { ENEMIES, getEnemy, getEnemiesByLevelRange, rollLoot };
