/**
 * Registry of every item in the game, keyed by snake_case item ID.
 *
 * Each entry describes a single item definition shared across all instances
 * of that item. Fields marked optional may be absent on items where they
 * do not apply.
 *
 * @type {Object<string, {
 *   id:              string,
 *   name:            string,
 *   slot:            string,
 *   type:            string,
 *   rarity:          string,
 *   lore:            boolean,
 *   nodrop:          boolean,
 *   weight:          number,
 *   classes:         Array<string>,
 *   races:           Array<string>,
 *   flavor:          string,
 *   dmg?:            number,
 *   delay?:          number,
 *   weaponType?:     string,
 *   ac?:             number,
 *   stats?:          object,
 *   resists?:        object,
 *   effect?:         string,
 *   capacity?:       number,
 *   weightReduction?: number
 * }>}
 *
 * @property {string}        id              - Snake_case identifier matching the map key.
 * @property {string}        name            - Display name shown in the UI.
 * @property {string}        slot            - Equipment slot: 'primary', 'secondary', 'head',
 *                                            'chest', 'legs', 'feet', 'bag', etc.
 * @property {string}        type            - Category: 'weapon', 'armor', 'consumable',
 *                                            'bag', 'tradeskill'.
 * @property {string}        rarity          - 'common', 'magic', 'rare', or 'named'.
 * @property {boolean}       lore            - If true, only one copy may be carried at a time.
 * @property {boolean}       nodrop          - If true, the item cannot be traded, sold, or banked.
 * @property {number}        weight          - Item weight contributing to encumbrance.
 * @property {Array<string>} classes         - Class IDs allowed to use this item; empty = all classes.
 * @property {Array<string>} races           - Race IDs allowed to use this item; empty = all races.
 * @property {string}        flavor          - Italic lore / flavor text displayed on the item tooltip.
 * @property {number}        [dmg]           - (Weapons) Base damage per hit.
 * @property {number}        [delay]         - (Weapons) Attack delay in tenths of a second.
 * @property {string}        [weaponType]    - (Weapons) Damage type: 'slash', 'pierce', 'blunt',
 *                                            or 'hand_to_hand'.
 * @property {number}        [ac]            - (Armor) Armor class value.
 * @property {object}        [stats]         - Optional attribute bonuses, e.g.
 *                                            { STR, DEX, AGI, STA, WIS, INT, CHA, hp, mana }.
 * @property {object}        [resists]       - Optional resist bonuses, e.g.
 *                                            { magic, fire, cold, poison, disease }.
 * @property {string}        [effect]        - On-use or worn effect name.
 * @property {number}        [capacity]      - (Bags) Number of item slots inside the bag.
 * @property {number}        [weightReduction] - (Bags) Percentage weight reduction applied to
 *                                            contents.
 */
const ITEMS = {
  // ─── WEAPONS ───────────────────────────────────────────────────────────────

  short_sword: {
    id: 'short_sword',
    name: 'Short Sword',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.5,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'bard', 'beastlord'],
    races: [],
    flavor: 'A reliable blade for those who prefer close combat.',
    dmg: 4,
    delay: 28,
    weaponType: 'slash',
  },

  hatchet: {
    id: 'hatchet',
    name: 'Hatchet',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.5,
    classes: ['warrior', 'berserker', 'ranger'],
    races: [],
    flavor: 'A compact chopping axe, useful in the field and in battle.',
    dmg: 5,
    delay: 30,
    weaponType: 'slash',
  },

  dagger: {
    id: 'dagger',
    name: 'Dagger',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: ['rogue', 'wizard', 'magician', 'necromancer', 'enchanter', 'bard'],
    races: [],
    flavor: 'Light and quick. Favored by those who value speed over brute force.',
    dmg: 3,
    delay: 20,
    weaponType: 'pierce',
  },

  fists: {
    id: 'fists',
    name: 'Fists',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0,
    classes: ['monk'],
    races: [],
    flavor: 'The body itself is the weapon.',
    dmg: 2,
    delay: 18,
    weaponType: 'hand_to_hand',
  },

  crude_spear: {
    id: 'crude_spear',
    name: 'Crude Spear',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 5.0,
    classes: ['warrior', 'beastlord', 'ranger'],
    races: [],
    flavor: 'A sharpened shaft of wood with a bone tip lashed at the end.',
    dmg: 4,
    delay: 32,
    weaponType: 'pierce',
  },

  gnarled_staff: {
    id: 'gnarled_staff',
    name: 'Gnarled Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: ['wizard', 'magician', 'necromancer', 'enchanter', 'druid', 'shaman'],
    races: [],
    flavor: 'A twisted walking staff repurposed as a focus for magical energies.',
    dmg: 2,
    delay: 40,
    weaponType: 'blunt',
  },

  crude_mace: {
    id: 'crude_mace',
    name: 'Crude Mace',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.5,
    classes: ['cleric', 'paladin', 'shadowknight', 'shaman'],
    races: [],
    flavor: 'A heavy iron head mounted on a short handle. Simple but effective.',
    dmg: 3,
    delay: 28,
    weaponType: 'blunt',
  },

  crude_staff: {
    id: 'crude_staff',
    name: 'Crude Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: ['druid', 'shaman', 'wizard', 'magician', 'necromancer', 'enchanter'],
    races: [],
    flavor: 'A straight-cut staff of ash wood, barely sanded smooth.',
    dmg: 2,
    delay: 36,
    weaponType: 'blunt',
  },

  simple_lute: {
    id: 'simple_lute',
    name: 'Simple Lute',
    slot: 'secondary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: ['bard'],
    races: [],
    flavor: 'A traveler\'s lute strung with gut strings. It carries a tune well enough.',
    dmg: 1,
    delay: 36,
    weaponType: 'blunt',
  },

  rusty_short_sword: {
    id: 'rusty_short_sword',
    name: 'Rusty Short Sword',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.5,
    classes: [],
    races: [],
    flavor: 'Pitted with rust but still functional.',
    dmg: 3,
    delay: 30,
    weaponType: 'slash',
  },

  tarnished_axe: {
    id: 'tarnished_axe',
    name: 'Tarnished Axe',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.5,
    classes: [],
    races: [],
    flavor: 'The edge is dull but the weight is substantial.',
    dmg: 4,
    delay: 32,
    weaponType: 'slash',
  },

  cracked_staff: {
    id: 'cracked_staff',
    name: 'Cracked Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.5,
    classes: [],
    races: [],
    flavor: 'Held together by will and a leather wrap.',
    dmg: 2,
    delay: 40,
    weaponType: 'blunt',
  },

  gnoll_slayer: {
    id: 'gnoll_slayer',
    name: 'Gnoll Slayer',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'bard'],
    races: [],
    flavor: 'Crafted from the fangs of a gnoll chieftain.',
    dmg: 4,
    delay: 27,
    weaponType: 'slash',
    stats: { STR: 2, DEX: 1 },
  },

  // ─── SHIELDS / OFFHAND ──────────────────────────────────────────────────────

  small_shield: {
    id: 'small_shield',
    name: 'Small Shield',
    slot: 'secondary',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: [],
    races: [],
    flavor: 'A round buckler of wood banded with iron.',
    ac: 5,
  },

  // ─── ARMOR: HEAD ───────────────────────────────────────────────────────────

  cloth_cap: {
    id: 'cloth_cap',
    name: 'Cloth Cap',
    slot: 'head',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.5,
    classes: [],
    races: [],
    flavor: 'A simple woven cap that keeps the sun off and not much else.',
    ac: 1,
  },

  crude_leather_cap: {
    id: 'crude_leather_cap',
    name: 'Crude Leather Cap',
    slot: 'head',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: [],
    races: [],
    flavor: 'A stiff leather cap stitched in haste.',
    ac: 2,
  },

  // ─── ARMOR: CHEST ──────────────────────────────────────────────────────────

  cloth_tunic: {
    id: 'cloth_tunic',
    name: 'Cloth Tunic',
    slot: 'chest',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 2.0,
    classes: ['wizard', 'magician', 'necromancer', 'enchanter', 'cleric', 'druid', 'shaman', 'bard'],
    races: [],
    flavor: 'Loose linen, comfortable and breathable.',
    ac: 2,
  },

  crude_leather_tunic: {
    id: 'crude_leather_tunic',
    name: 'Crude Leather Tunic',
    slot: 'chest',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: [],
    races: [],
    flavor: 'Stiff boiled leather pieced together with gut cord.',
    ac: 4,
  },

  // ─── ARMOR: LEGS ───────────────────────────────────────────────────────────

  cloth_pants: {
    id: 'cloth_pants',
    name: 'Cloth Pants',
    slot: 'legs',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: [],
    races: [],
    flavor: 'Plain woven trousers. Little protection but better than nothing.',
    ac: 1,
  },

  // ─── ARMOR: FEET ───────────────────────────────────────────────────────────

  simple_boots: {
    id: 'simple_boots',
    name: 'Simple Boots',
    slot: 'feet',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.5,
    classes: [],
    races: [],
    flavor: 'Soft-soled leather boots worn smooth at the heel.',
    ac: 1,
  },

  // ─── JEWELRY ───────────────────────────────────────────────────────────────

  fishbone_earring: {
    id: 'fishbone_earring',
    name: 'Fishbone Earring',
    slot: 'ear1',
    type: 'jewelry',
    rarity: 'named',
    lore: true,
    nodrop: true,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A strange earring made from fish bones. Allows breathing underwater.',
    stats: {},
    effect: 'Enduring Breath',
  },

  glowing_black_stone: {
    id: 'glowing_black_stone',
    name: 'Glowing Black Stone',
    slot: 'ring1',
    type: 'jewelry',
    rarity: 'rare',
    lore: true,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A smooth obsidian stone that pulses with dark energy.',
    stats: { INT: 9 },
    resists: { magic: 10, fire: 0, cold: 0, poison: 0, disease: 0 },
  },

  // ─── MATERIALS / LOOT ──────────────────────────────────────────────────────

  bone_chips: {
    id: 'bone_chips',
    name: 'Bone Chips',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Cracked bones from an undead creature.',
  },

  gnoll_tooth: {
    id: 'gnoll_tooth',
    name: 'Gnoll Tooth',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Sharp and yellowed.',
  },

  gnoll_fang: {
    id: 'gnoll_fang',
    name: 'Gnoll Fang',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A curved fang from an adult gnoll.',
  },

  fire_beetle_eye: {
    id: 'fire_beetle_eye',
    name: 'Fire Beetle Eye',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Used in alchemy. Warm to the touch.',
  },

  bat_wing: {
    id: 'bat_wing',
    name: 'Bat Wing',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Thin and membranous.',
  },

  wolf_pelt: {
    id: 'wolf_pelt',
    name: 'Wolf Pelt',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.5,
    classes: [],
    races: [],
    flavor: 'A grey pelt, still warm.',
  },

  bear_pelt: {
    id: 'bear_pelt',
    name: 'Bear Pelt',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: [],
    races: [],
    flavor: 'A thick, heavy pelt.',
  },

  rat_pelt: {
    id: 'rat_pelt',
    name: 'Rat Pelt',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.3,
    classes: [],
    races: [],
    flavor: 'Small and mangy.',
  },

  snake_scale: {
    id: 'snake_scale',
    name: 'Snake Scale',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Smooth and iridescent.',
  },

  // ─── CURRENCY ──────────────────────────────────────────────────────────────

  silver_coin: {
    id: 'silver_coin',
    name: 'Silver Coin',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.01,
    classes: [],
    races: [],
    flavor: 'Standard silver coinage.',
  },

  copper_coin: {
    id: 'copper_coin',
    name: 'Copper Coin',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.01,
    classes: [],
    races: [],
    flavor: 'Worn copper currency.',
  },

  // ─── BAGS ──────────────────────────────────────────────────────────────────

  small_pouch: {
    id: 'small_pouch',
    name: 'Small Pouch',
    slot: 'bag',
    type: 'bag',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.5,
    capacity: 4,
    weightReduction: 0,
    classes: [],
    races: [],
    flavor: 'A simple cloth pouch. Holds a few items.',
  },

  large_pouch: {
    id: 'large_pouch',
    name: 'Large Pouch',
    slot: 'bag',
    type: 'bag',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.0,
    capacity: 8,
    weightReduction: 0,
    classes: [],
    races: [],
    flavor: 'A large leather pouch with several compartments.',
  },

  travelers_pack: {
    id: 'travelers_pack',
    name: "Traveler's Pack",
    slot: 'bag',
    type: 'bag',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 2.0,
    capacity: 10,
    weightReduction: 10,
    classes: [],
    races: [],
    flavor: "A well-crafted adventurer's pack. Items inside weigh a bit less.",
  },

  // ─── BLACKBURROW LOOT ──────────────────────────────────────────────────────

  gnoll_shaman_beads: {
    id: 'gnoll_shaman_beads',
    name: 'Gnoll Shaman Beads',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Strung bone and fang beads used in gnoll shamanistic rituals.',
  },

  gnoll_shaman_staff: {
    id: 'gnoll_shaman_staff',
    name: 'Gnoll Shaman Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 3.5,
    classes: ['shaman', 'druid', 'cleric'],
    races: [],
    flavor: 'A crude staff topped with fetishes and bone. Faintly hums with dark energy.',
    dmg: 3,
    delay: 38,
    weaponType: 'blunt',
    stats: { WIS: 2 },
  },

  gnoll_high_shaman_staff: {
    id: 'gnoll_high_shaman_staff',
    name: 'Gnoll High Shaman Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: true,
    nodrop: false,
    weight: 3.5,
    classes: ['shaman', 'druid', 'cleric', 'necromancer'],
    races: [],
    flavor: "The staff of Blackburrow's high shaman, pulsing with dark channeled power.",
    dmg: 5,
    delay: 36,
    weaponType: 'blunt',
    stats: { WIS: 4, INT: 2 },
  },

  bb_gnoll_guard_shield: {
    id: 'bb_gnoll_guard_shield',
    name: 'Gnoll Guard Shield',
    slot: 'secondary',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 5.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'cleric', 'bard'],
    races: [],
    flavor: 'A battered shield scavenged from a fallen gnoll guard. Still serviceable.',
    ac: 7,
  },

  elite_gnoll_helm: {
    id: 'elite_gnoll_helm',
    name: 'Elite Gnoll Helm',
    slot: 'head',
    type: 'armor',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'bard'],
    races: [],
    flavor: "Forged deep in Blackburrow's smithy. Dented but proudly worn by the elite guard.",
    ac: 8,
    stats: { STA: 2 },
  },

  blackburrow_stout: {
    id: 'blackburrow_stout',
    name: 'Blackburrow Stout',
    slot: 'inventory',
    type: 'consumable',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.5,
    classes: [],
    races: [],
    flavor: "A dark, bitter ale brewed deep in the warrens. Famous across Norrath — if you can stomach the source.",
  },

  elgnubs_gnoll_hide_belt: {
    id: 'elgnubs_gnoll_hide_belt',
    name: "Elgnub's Gnoll Hide Belt",
    slot: 'waist',
    type: 'armor',
    rarity: 'named',
    lore: true,
    nodrop: false,
    weight: 1.0,
    classes: [],
    races: [],
    flavor: 'The personal belt of Lord Elgnub, fashioned from the hides of defeated enemies.',
    ac: 5,
    stats: { STA: 3, STR: 2 },
  },

  lords_insignia_ring: {
    id: 'lords_insignia_ring',
    name: "Lord's Insignia Ring",
    slot: 'ring1',
    type: 'jewelry',
    rarity: 'named',
    lore: true,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A heavy iron ring bearing the seal of Lord Elgnub. A mark of authority in Blackburrow.',
    stats: { STR: 3, STA: 2 },
    resists: { magic: 5, fire: 0, cold: 0, poison: 0, disease: 0 },
  },

  commanders_sword: {
    id: 'commanders_sword',
    name: "Commander's Sword",
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'bard'],
    races: [],
    flavor: 'A well-balanced blade carried by the gnoll commander. Its edge is unnervingly sharp.',
    dmg: 7,
    delay: 28,
    weaponType: 'slash',
    stats: { STR: 2 },
  },

  gold_coin: {
    id: 'gold_coin',
    name: 'Gold Coin',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.01,
    classes: [],
    races: [],
    flavor: 'Gleaming gold currency.',
  },

  bread_loaf: {
    id: 'bread_loaf',
    name: 'Bread Loaf',
    slot: 'inventory',
    type: 'food',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    ac: 0,
    classes: [],
    races: [],
    flavor: 'A fresh-baked loaf from the bakers of Qeynos. Restores your strength.',
  },

  giant_snake_fang: {
    id: 'giant_snake_fang',
    name: 'Giant Snake Fang',
    slot: 'inventory',
    type: 'loot',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 0.5,
    classes: [],
    races: [],
    flavor: 'A yellowed fang from a Blackburrow constrictor. Prized by alchemists.',
  },

  blackburrow_stout: {
    id: 'blackburrow_stout',
    name: 'Blackburrow Stout',
    slot: 'inventory',
    type: 'loot',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: [],
    races: [],
    flavor: 'A cask of thick, bitter gnoll brew. Smells terrible. Worth coin to collectors.',
  },

  gold_coin: {
    id: 'gold_coin',
    name: 'Gold Coin',
    slot: 'inventory',
    type: 'currency',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A shining gold coin.',
  },

  spiked_collar: {
    id: 'spiked_collar',
    name: 'Spiked Collar',
    slot: 'neck',
    type: 'armor',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'monk', 'bard', 'berserker', 'beastlord'],
    races: [],
    flavor: 'A gnoll-crafted collar studded with bone spikes.',
    ac: 3,
    stats: { STR: 3 },
  },

  gnoll_hide_lariat: {
    id: 'gnoll_hide_lariat',
    name: 'Gnoll Hide Lariat',
    slot: 'primary',
    type: 'weapon',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'bard', 'beastlord', 'monk'],
    races: [],
    flavor: 'A short whip braided from gnoll hide. Crude but effective.',
    dmg: 3,
    delay: 30,
    weaponType: 'slash',
    stats: {},
  },

  runed_totem_staff: {
    id: 'runed_totem_staff',
    name: 'Runed Totem Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 6.0,
    classes: ['cleric', 'druid', 'shaman', 'necromancer', 'wizard', 'magician', 'enchanter'],
    races: [],
    flavor: 'A carved totem staff crackling with latent gnoll magic.',
    dmg: 9,
    delay: 40,
    weaponType: 'blunt',
    stats: { hp: 5, mana: 5 },
  },

  // ─── EVERFROST PEAKS — WEAPONS ─────────────────────────────────────────────

  frost_goblin_shiv: {
    id: 'frost_goblin_shiv',
    name: 'Frost Goblin Shiv',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.5,
    classes: ['rogue', 'bard', 'wizard', 'magician', 'necromancer', 'enchanter'],
    races: [],
    flavor: 'A crude ice-hardened shiv fashioned from a frozen goblin fang.',
    dmg: 3,
    delay: 22,
    weaponType: 'pierce',
  },

  ice_wolf_claw: {
    id: 'ice_wolf_claw',
    name: 'Ice Wolf Claw',
    slot: 'primary',
    type: 'weapon',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 2.0,
    classes: ['warrior', 'ranger', 'rogue', 'monk', 'beastlord'],
    races: [],
    flavor: 'A razor-sharp claw torn from an ice wolf. Still cold to the touch.',
    dmg: 5,
    delay: 24,
    weaponType: 'slash',
    stats: { DEX: 2 },
  },

  frozen_bone_club: {
    id: 'frozen_bone_club',
    name: 'Frozen Bone Club',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'cleric', 'shaman'],
    races: [],
    flavor: 'A club fashioned from frozen bones bound with sinew.',
    dmg: 6,
    delay: 35,
    weaponType: 'blunt',
  },

  everfrost_spear: {
    id: 'everfrost_spear',
    name: 'Everfrost Spear',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 5.5,
    classes: ['warrior', 'ranger', 'beastlord'],
    races: [],
    flavor: 'A spear tipped with enchanted ice that never melts.',
    dmg: 8,
    delay: 30,
    weaponType: 'pierce',
    stats: { STR: 3, AGI: 2 },
  },

  spectral_blade: {
    id: 'spectral_blade',
    name: 'Spectral Blade',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: true,
    nodrop: false,
    weight: 3.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'bard'],
    races: [],
    flavor: 'A blade forged from the essence of a permafrost spectre. Phases in and out of reality.',
    dmg: 9,
    delay: 26,
    weaponType: 'slash',
    stats: { DEX: 3, INT: 2 },
  },

  ice_giant_maul: {
    id: 'ice_giant_maul',
    name: 'Ice Giant Maul',
    slot: 'primary',
    type: 'weapon',
    rarity: 'rare',
    lore: true,
    nodrop: false,
    weight: 12.0,
    classes: ['warrior', 'berserker', 'shadowknight'],
    races: [],
    flavor: 'A massive maul wielded by the ice giant scouts. Requires tremendous strength.',
    dmg: 18,
    delay: 50,
    weaponType: 'blunt',
    stats: { STR: 6, STA: 4 },
  },

  mammoth_ivory_staff: {
    id: 'mammoth_ivory_staff',
    name: 'Mammoth Ivory Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 6.0,
    classes: ['druid', 'shaman', 'wizard', 'magician', 'necromancer', 'enchanter', 'cleric'],
    races: [],
    flavor: 'A staff carved from mammoth ivory, radiating natural power.',
    dmg: 6,
    delay: 38,
    weaponType: 'blunt',
    stats: { WIS: 4, INT: 4, mana: 20 },
  },

  // ─── EVERFROST PEAKS — ARMOR ───────────────────────────────────────────────

  frost_goblin_cap: {
    id: 'frost_goblin_cap',
    name: 'Frost Goblin Cap',
    slot: 'head',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 2.0,
    classes: [],
    races: [],
    flavor: 'A crude cap stitched from frost goblin hide.',
    ac: 4,
  },

  ice_wolf_pelt: {
    id: 'ice_wolf_pelt',
    name: 'Ice Wolf Pelt',
    slot: 'chest',
    type: 'armor',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 5.0,
    classes: ['warrior', 'ranger', 'rogue', 'bard', 'beastlord', 'monk'],
    races: [],
    flavor: 'A thick pelt from an ice wolf. Provides surprising warmth and protection.',
    ac: 8,
    stats: { STA: 2, AGI: 2 },
  },

  frozen_bone_pauldrons: {
    id: 'frozen_bone_pauldrons',
    name: 'Frozen Bone Pauldrons',
    slot: 'shoulders',
    type: 'armor',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'berserker'],
    races: [],
    flavor: 'Shoulder guards crafted from the bones of frozen undead.',
    ac: 7,
    stats: { STR: 2 },
  },

  everfrost_ringmail_tunic: {
    id: 'everfrost_ringmail_tunic',
    name: 'Everfrost Ringmail Tunic',
    slot: 'chest',
    type: 'armor',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 8.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'bard', 'beastlord', 'berserker'],
    races: [],
    flavor: 'Ringmail reinforced with enchanted frost crystals.',
    ac: 12,
    stats: { STA: 3 },
    resists: { magic: 0, fire: 0, cold: 10, poison: 0, disease: 0 },
  },

  spectre_shroud: {
    id: 'spectre_shroud',
    name: 'Spectre Shroud',
    slot: 'back',
    type: 'armor',
    rarity: 'magic',
    lore: true,
    nodrop: false,
    weight: 1.5,
    classes: ['necromancer', 'shadowknight', 'enchanter', 'wizard'],
    races: [],
    flavor: 'A cloak woven from spectral energy. Cold to the touch, warm to the spirit.',
    ac: 5,
    stats: { INT: 4, WIS: 2, mana: 30 },
  },

  mammoth_hide_boots: {
    id: 'mammoth_hide_boots',
    name: 'Mammoth Hide Boots',
    slot: 'feet',
    type: 'armor',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: [],
    races: [],
    flavor: 'Boots made from mammoth hide. Your feet will never be cold again.',
    ac: 5,
    stats: { STA: 2 },
    resists: { magic: 0, fire: 0, cold: 5, poison: 0, disease: 0 },
  },

  ice_giant_bracer: {
    id: 'ice_giant_bracer',
    name: 'Ice Giant Bracer',
    slot: 'wrist_l',
    type: 'armor',
    rarity: 'rare',
    lore: true,
    nodrop: false,
    weight: 3.5,
    classes: ['warrior', 'berserker', 'paladin', 'shadowknight'],
    races: [],
    flavor: 'A bracer looted from an ice giant scout. Far too large, but magically resized.',
    ac: 9,
    stats: { STR: 4, STA: 3 },
  },

  // ─── EVERFROST PEAKS — JEWELRY ─────────────────────────────────────────────

  frost_crystal_ring: {
    id: 'frost_crystal_ring',
    name: 'Frost Crystal Ring',
    slot: 'ring1',
    type: 'armor',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A ring set with a frost crystal that pulses with cold magic.',
    ac: 0,
    stats: { INT: 3, WIS: 3 },
    resists: { magic: 0, fire: 0, cold: 8, poison: 0, disease: 0 },
  },

  everfrost_amulet: {
    id: 'everfrost_amulet',
    name: 'Everfrost Amulet',
    slot: 'neck',
    type: 'armor',
    rarity: 'magic',
    lore: true,
    nodrop: false,
    weight: 0.2,
    classes: [],
    races: [],
    flavor: 'An amulet from the depths of Everfrost. Radiates a numbing cold.',
    ac: 2,
    stats: { STA: 4 },
    resists: { magic: 0, fire: 0, cold: 15, poison: 0, disease: 5 },
  },

  // ── West Karana ────────────────────────────────────────────────────────────

  cloth_scraps: {
    id: 'cloth_scraps',
    name: 'Cloth Scraps',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Scraps of worn cloth, useful for basic crafting.',
  },

  bandit_shortsword: {
    id: 'bandit_shortsword',
    name: 'Bandit Shortsword',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'bard', 'beastlord'],
    races: [],
    flavor: 'A short sword stolen from an unlucky traveler.',
    dmg: 8,
    delay: 28,
    weaponType: 'slash',
  },

  raider_axe: {
    id: 'raider_axe',
    name: 'Raider Axe',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 5.0,
    classes: ['warrior', 'berserker', 'ranger'],
    races: [],
    flavor: 'A heavy axe favored by Karana raiders.',
    dmg: 10,
    delay: 32,
    weaponType: 'slash',
  },

  giant_wolf_pelt: {
    id: 'giant_wolf_pelt',
    name: 'Giant Wolf Pelt',
    slot: 'chest',
    type: 'armor',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 3.5,
    classes: [],
    races: [],
    flavor: 'The thick pelt of a giant wolf, still warm to the touch.',
    ac: 10,
    stats: { STA: 3 },
  },

  griffon_feather: {
    id: 'griffon_feather',
    name: 'Griffon Feather',
    slot: 'neck',
    type: 'armor',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A large iridescent feather from a plains griffon.',
    ac: 0,
    stats: { AGI: 5, DEX: 3 },
  },

  griffon_talon: {
    id: 'griffon_talon',
    name: 'Griffon Talon',
    slot: 'primary',
    type: 'weapon',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 1.5,
    classes: ['rogue', 'bard', 'ranger'],
    races: [],
    flavor: 'A razor-sharp griffon talon fashioned into a blade.',
    dmg: 9,
    delay: 25,
    weaponType: 'pierce',
  },

  gnoll_war_club: {
    id: 'gnoll_war_club',
    name: 'Gnoll War Club',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 6.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'berserker'],
    races: [],
    flavor: 'A crude but effective war club used by gnoll warriors.',
    dmg: 11,
    delay: 35,
    weaponType: 'blunt',
  },

  cyclops_eye: {
    id: 'cyclops_eye',
    name: 'Cyclops Eye',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.5,
    classes: [],
    races: [],
    flavor: 'The preserved eye of a plains cyclops. Rumored to have mystical properties.',
  },

  cyclops_hide_belt: {
    id: 'cyclops_hide_belt',
    name: 'Cyclops Hide Belt',
    slot: 'waist',
    type: 'armor',
    rarity: 'named',
    lore: true,
    nodrop: false,
    weight: 2.0,
    classes: [],
    races: [],
    flavor: 'A belt of extraordinary quality crafted from cyclops hide.',
    ac: 7,
    stats: { STA: 5, STR: 4 },
  },

  dust_goblin_cap: {
    id: 'dust_goblin_cap',
    name: 'Dust Goblin Cap',
    slot: 'head',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.5,
    classes: [],
    races: [],
    flavor: 'A patchy cap worn by dust goblins, surprisingly durable.',
    ac: 5,
    stats: { DEX: 2 },
  },

  // ── Highpass Hold ──────────────────────────────────────────────────────────

  guard_short_sword: {
    id: 'guard_short_sword',
    name: 'Guard Short Sword',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.5,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'bard'],
    races: [],
    flavor: 'Standard issue sword of the Highpass guard.',
    dmg: 10,
    delay: 28,
    weaponType: 'slash',
  },

  guard_chainmail: {
    id: 'guard_chainmail',
    name: 'Guard Chainmail',
    slot: 'chest',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 8.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'bard', 'berserker'],
    races: [],
    flavor: 'Chainmail worn by Highpass garrison soldiers.',
    ac: 14,
    stats: { STA: 3 },
  },

  pass_bandit_blade: {
    id: 'pass_bandit_blade',
    name: 'Pass Bandit Blade',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'bard', 'berserker'],
    races: [],
    flavor: 'A blade notched from many ambushes in the mountain pass.',
    dmg: 12,
    delay: 30,
    weaponType: 'slash',
  },

  war_chief_axe: {
    id: 'war_chief_axe',
    name: 'War Chief Axe',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 5.5,
    classes: ['warrior', 'berserker', 'ranger', 'shadowknight'],
    races: [],
    flavor: 'The axe of the gnoll war chief, inscribed with battle runes.',
    dmg: 14,
    delay: 30,
    weaponType: 'slash',
    stats: { STR: 4, DEX: 2 },
  },

  gnoll_war_totem: {
    id: 'gnoll_war_totem',
    name: 'Gnoll War Totem',
    slot: 'secondary',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 2.5,
    classes: ['shaman', 'cleric', 'druid'],
    races: [],
    flavor: 'A carved totem used by gnoll war shamans in battle.',
    ac: 8,
    stats: { WIS: 5 },
  },

  thick_bear_pelt: {
    id: 'thick_bear_pelt',
    name: 'Thick Bear Pelt',
    slot: 'chest',
    type: 'armor',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: [],
    races: [],
    flavor: 'An exceptionally thick pelt from a mountain bear.',
    ac: 12,
    stats: { STA: 5 },
  },

  bear_claw: {
    id: 'bear_claw',
    name: 'Bear Claw',
    slot: 'primary',
    type: 'weapon',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: ['rogue', 'ranger', 'monk'],
    races: [],
    flavor: 'A fearsome bear claw honed to a deadly point.',
    dmg: 10,
    delay: 24,
    weaponType: 'pierce',
  },

  bone_chips: {
    id: 'bone_chips',
    name: 'Bone Chips',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Fragments of old bone, sought by necromancers and alchemists.',
  },

  old_sword: {
    id: 'old_sword',
    name: 'Old Sword',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: [],
    races: [],
    flavor: 'A worn and pitted sword from a forgotten battle.',
    dmg: 9,
    delay: 30,
    weaponType: 'slash',
  },

  troll_hide_tunic: {
    id: 'troll_hide_tunic',
    name: 'Troll Hide Tunic',
    slot: 'chest',
    type: 'armor',
    rarity: 'named',
    lore: true,
    nodrop: false,
    weight: 7.0,
    classes: ['warrior', 'berserker', 'paladin', 'shadowknight'],
    races: [],
    flavor: 'Armor crafted from rock troll hide. Extraordinarily tough.',
    ac: 18,
    stats: { STA: 7, STR: 3 },
  },

  troll_smash_club: {
    id: 'troll_smash_club',
    name: 'Troll Smash Club',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 9.0,
    classes: ['warrior', 'berserker', 'paladin', 'shadowknight'],
    races: [],
    flavor: 'A massive war club torn from a rock troll\'s grasp.',
    dmg: 16,
    delay: 40,
    weaponType: 'blunt',
    stats: { STR: 6 },
  },

  // ── Kithicor Forest ────────────────────────────────────────────────────────

  spirit_dust: {
    id: 'spirit_dust',
    name: 'Spirit Dust',
    slot: 'inventory',
    type: 'material',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Glowing dust left behind when a spirit is dispersed. Used in dark rituals.',
  },

  rotting_flesh: {
    id: 'rotting_flesh',
    name: 'Rotting Flesh',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.5,
    classes: [],
    races: [],
    flavor: 'A chunk of decaying flesh. It has no pleasant uses.',
  },

  spirit_sword: {
    id: 'spirit_sword',
    name: 'Spirit Sword',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: true,
    nodrop: false,
    weight: 3.0,
    classes: ['warrior', 'shadowknight', 'necromancer', 'bard'],
    races: [],
    flavor: 'A blade that phases between the material and spirit planes.',
    dmg: 15,
    delay: 28,
    weaponType: 'slash',
    stats: { STR: 3, INT: 3 },
  },

  spirit_essence: {
    id: 'spirit_essence',
    name: 'Spirit Essence',
    slot: 'neck',
    type: 'armor',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Crystallized essence of a warrior spirit, thrumming with energy.',
    ac: 2,
    stats: { INT: 5, WIS: 5 },
  },

  treant_bark: {
    id: 'treant_bark',
    name: 'Treant Bark',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: [],
    races: [],
    flavor: 'Bark from a corrupted treant. Dark magic seeps from its pores.',
  },

  treant_heartwood: {
    id: 'treant_heartwood',
    name: 'Treant Heartwood',
    slot: 'chest',
    type: 'armor',
    rarity: 'rare',
    lore: true,
    nodrop: false,
    weight: 4.0,
    classes: ['ranger', 'druid', 'beastlord', 'monk'],
    races: [],
    flavor: 'The heartwood of an ancient treant. Living magic pulses within it.',
    ac: 16,
    stats: { STA: 6, AGI: 4 },
  },

  dark_elf_blade: {
    id: 'dark_elf_blade',
    name: 'Dark Elf Blade',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 2.5,
    classes: ['shadowknight', 'rogue', 'bard', 'ranger'],
    races: [],
    flavor: 'A darksteel blade of Teir\'Dal craftsmanship. Supernaturally sharp.',
    dmg: 16,
    delay: 26,
    weaponType: 'slash',
    stats: { DEX: 4, AGI: 3 },
  },

  dark_elf_cloak: {
    id: 'dark_elf_cloak',
    name: 'Dark Elf Cloak',
    slot: 'back',
    type: 'armor',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 0.5,
    classes: [],
    races: [],
    flavor: 'A cloak woven from shadow-silk by dark elf craftsmen.',
    ac: 10,
    stats: { AGI: 5, DEX: 3 },
  },

  kill_anaz_greatsword: {
    id: 'kill_anaz_greatsword',
    name: 'Kill-Anaz Greatsword',
    slot: 'primary',
    type: 'weapon',
    rarity: 'named',
    lore: true,
    nodrop: false,
    weight: 12.0,
    classes: ['warrior', 'berserker', 'paladin', 'shadowknight'],
    races: [],
    flavor: 'The greatsword of General Kill-Anaz. Still carries the chill of death.',
    dmg: 22,
    delay: 38,
    weaponType: 'slash',
    stats: { STR: 8, STA: 5 },
  },

  spectral_plate_chest: {
    id: 'spectral_plate_chest',
    name: 'Spectral Plate Chest',
    slot: 'chest',
    type: 'armor',
    rarity: 'named',
    lore: true,
    nodrop: false,
    weight: 10.0,
    classes: ['warrior', 'paladin', 'shadowknight'],
    races: [],
    flavor: 'Ethereal plate armor worn by the general\'s spirit. Solid to the touch despite its ghostly appearance.',
    ac: 24,
    stats: { STA: 10, STR: 5 },
  },

  // ── Commonlands ────────────────────────────────────────────────────────────

  orc_war_blade: {
    id: 'orc_war_blade',
    name: 'Orc War Blade',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 5.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'berserker'],
    races: [],
    flavor: 'A heavy blade forged by Crushbone orc smiths.',
    dmg: 17,
    delay: 30,
    weaponType: 'slash',
  },

  orc_hide_armor: {
    id: 'orc_hide_armor',
    name: 'Orc Hide Armor',
    slot: 'chest',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 5.0,
    classes: [],
    races: [],
    flavor: 'Rough armor stitched from orc-tanned hides.',
    ac: 13,
    stats: { STA: 4 },
  },

  orc_shaman_staff: {
    id: 'orc_shaman_staff',
    name: 'Orc Shaman Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 5.0,
    classes: ['shaman', 'druid', 'cleric', 'necromancer'],
    races: [],
    flavor: 'A staff topped with a glowing green orb used in orc shamanistic rituals.',
    dmg: 14,
    delay: 38,
    weaponType: 'blunt',
    stats: { WIS: 6, INT: 4 },
  },

  orc_shaman_beads: {
    id: 'orc_shaman_beads',
    name: 'Orc Shaman Beads',
    slot: 'neck',
    type: 'armor',
    rarity: 'magic',
    lore: true,
    nodrop: false,
    weight: 0.2,
    classes: ['shaman', 'cleric', 'druid', 'wizard', 'necromancer', 'enchanter', 'magician'],
    races: [],
    flavor: 'Prayer beads strung with carved bone. Powerful focus for divine magic.',
    ac: 3,
    stats: { WIS: 8 },
  },

  captain_sword: {
    id: 'captain_sword',
    name: 'Captain Sword',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 4.5,
    classes: ['warrior', 'paladin', 'shadowknight', 'bard'],
    races: [],
    flavor: 'The ceremonial sword of an orc captain. Enhanced with battle magic.',
    dmg: 19,
    delay: 28,
    weaponType: 'slash',
    stats: { STR: 5, DEX: 4 },
  },

  captain_shield: {
    id: 'captain_shield',
    name: 'Captain Shield',
    slot: 'secondary',
    type: 'armor',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 6.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'cleric'],
    races: [],
    flavor: 'A heavy shield marked with the Crushbone crest.',
    ac: 18,
    stats: { STA: 6 },
  },

  lion_pelt: {
    id: 'lion_pelt',
    name: 'Lion Pelt',
    slot: 'chest',
    type: 'armor',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: [],
    races: [],
    flavor: 'A magnificent pelt from a Commonlands lion. Warm and supple.',
    ac: 14,
    stats: { AGI: 5 },
  },

  lion_claw: {
    id: 'lion_claw',
    name: 'Lion Claw',
    slot: 'primary',
    type: 'weapon',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: ['rogue', 'ranger', 'monk', 'beastlord'],
    races: [],
    flavor: 'A lion\'s retractable claw removed at the root. Viciously sharp.',
    dmg: 14,
    delay: 23,
    weaponType: 'pierce',
  },

  dark_elf_longbow: {
    id: 'dark_elf_longbow',
    name: 'Dark Elf Longbow',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: ['ranger', 'rogue'],
    races: [],
    flavor: 'A composite longbow of Teir\'Dal design. Near-silent when drawn.',
    dmg: 16,
    delay: 30,
    weaponType: 'pierce',
    stats: { DEX: 5 },
  },

  dark_elf_quiver: {
    id: 'dark_elf_quiver',
    name: 'Dark Elf Quiver',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.5,
    classes: [],
    races: [],
    flavor: 'A quiver of dark elf arrows. Black-fletched and expertly balanced.',
  },

  warlord_axe: {
    id: 'warlord_axe',
    name: 'Warlord Axe',
    slot: 'primary',
    type: 'weapon',
    rarity: 'named',
    lore: true,
    nodrop: false,
    weight: 11.0,
    classes: ['warrior', 'berserker', 'paladin', 'shadowknight'],
    races: [],
    flavor: 'The great axe of the Crushbone Warlord. Its edge never dulls.',
    dmg: 24,
    delay: 34,
    weaponType: 'slash',
    stats: { STR: 10, STA: 6 },
  },

  crushbone_shoulderplates: {
    id: 'crushbone_shoulderplates',
    name: 'Crushbone Shoulderplates',
    slot: 'shoulders',
    type: 'armor',
    rarity: 'named',
    lore: true,
    nodrop: false,
    weight: 8.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'berserker'],
    races: [],
    flavor: 'Massive shoulderplates bearing the Crushbone mark of conquest.',
    ac: 22,
    stats: { STR: 8, STA: 8 },
  },

  plague_shroud: {
    id: 'plague_shroud',
    name: 'Plague Shroud',
    slot: 'back',
    type: 'armor',
    rarity: 'named',
    lore: true,
    nodrop: false,
    weight: 1.0,
    classes: ['necromancer', 'wizard', 'enchanter', 'magician'],
    races: [],
    flavor: 'A cloak saturated with plague magic. Those who touch it risk disease.',
    ac: 15,
    stats: { STA: 8, INT: 8 },
  },

  spectre_essence_ring: {
    id: 'spectre_essence_ring',
    name: 'Spectre Essence Ring',
    slot: 'ring1',
    type: 'armor',
    rarity: 'named',
    lore: true,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A ring formed from crystallized spectre essence. Throbs with dark power.',
    ac: 0,
    stats: { INT: 10, WIS: 10 },
  },
};

/**
 * Maps each class ID to the ordered list of item IDs equipped on that class
 * when a new character is created.  Items are applied in array order, so
 * earlier entries take priority if slot conflicts arise.
 *
 * @type {Object<string, Array<string>>}
 */
const STARTING_GEAR = {
  warrior:     ['short_sword', 'small_shield', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  paladin:     ['short_sword', 'small_shield', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  shadowknight:['short_sword', 'small_shield', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  berserker:   ['hatchet', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  rogue:       ['dagger', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  monk:        ['fists', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  ranger:      ['short_sword', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  bard:        ['short_sword', 'simple_lute', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  beastlord:   ['crude_spear', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  wizard:      ['gnarled_staff', 'cloth_cap', 'cloth_tunic', 'cloth_pants', 'simple_boots'],
  magician:    ['gnarled_staff', 'cloth_cap', 'cloth_tunic', 'cloth_pants', 'simple_boots'],
  necromancer: ['gnarled_staff', 'cloth_cap', 'cloth_tunic', 'cloth_pants', 'simple_boots'],
  enchanter:   ['gnarled_staff', 'cloth_cap', 'cloth_tunic', 'cloth_pants', 'simple_boots'],
  cleric:      ['crude_mace', 'small_shield', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  druid:       ['crude_staff', 'cloth_cap', 'cloth_tunic', 'cloth_pants', 'simple_boots'],
  shaman:      ['crude_staff', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
};

/**
 * Retrieves a single item definition by its snake_case ID.
 *
 * @param {string} id - The snake_case item ID to look up.
 * @returns {object|null} The item definition object, or null if not found.
 */
function getItemById(id) {
  return ITEMS[id] || null;
}

/**
 * Creates a lightweight inventory stack descriptor for the given item.
 *
 * @param {string} itemId    - The snake_case ID of the item.
 * @param {number} [quantity=1] - Number of items in the stack.
 * @returns {{ itemId: string, quantity: number, item: object }} Stack descriptor
 *   containing the item ID, quantity, and the full item definition object.
 */
function createInventoryStack(itemId, quantity = 1) {
  return { itemId, quantity, item: ITEMS[itemId] };
}

if (typeof module !== 'undefined') module.exports = { ITEMS, STARTING_GEAR, getItemById, createInventoryStack };
