const ITEMS = {
  // ─── WEAPONS ───────────────────────────────────────────────────────────────

  short_sword: {
    id: 'short_sword',
    name: 'Short Sword',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.5,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'bard', 'beastlord'],
    races: [],
    flavor: 'A reliable blade for those who prefer close combat.',
    dmg: 4,
    delay: 28,
    weaponType: 'slash',
  },

  hatchet: {
    id: 'hatchet',
    name: 'Hatchet',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.5,
    classes: ['warrior', 'berserker', 'ranger'],
    races: [],
    flavor: 'A compact chopping axe, useful in the field and in battle.',
    dmg: 5,
    delay: 30,
    weaponType: 'slash',
  },

  dagger: {
    id: 'dagger',
    name: 'Dagger',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: ['rogue', 'wizard', 'magician', 'necromancer', 'enchanter', 'bard'],
    races: [],
    flavor: 'Light and quick. Favored by those who value speed over brute force.',
    dmg: 3,
    delay: 20,
    weaponType: 'pierce',
  },

  fists: {
    id: 'fists',
    name: 'Fists',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0,
    classes: ['monk'],
    races: [],
    flavor: 'The body itself is the weapon.',
    dmg: 2,
    delay: 18,
    weaponType: 'hand_to_hand',
  },

  crude_spear: {
    id: 'crude_spear',
    name: 'Crude Spear',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 5.0,
    classes: ['warrior', 'beastlord', 'ranger'],
    races: [],
    flavor: 'A sharpened shaft of wood with a bone tip lashed at the end.',
    dmg: 4,
    delay: 32,
    weaponType: 'pierce',
  },

  gnarled_staff: {
    id: 'gnarled_staff',
    name: 'Gnarled Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: ['wizard', 'magician', 'necromancer', 'enchanter', 'druid', 'shaman'],
    races: [],
    flavor: 'A twisted walking staff repurposed as a focus for magical energies.',
    dmg: 2,
    delay: 40,
    weaponType: 'blunt',
  },

  crude_mace: {
    id: 'crude_mace',
    name: 'Crude Mace',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.5,
    classes: ['cleric', 'paladin', 'shadowknight', 'shaman'],
    races: [],
    flavor: 'A heavy iron head mounted on a short handle. Simple but effective.',
    dmg: 3,
    delay: 28,
    weaponType: 'blunt',
  },

  crude_staff: {
    id: 'crude_staff',
    name: 'Crude Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: ['druid', 'shaman', 'wizard', 'magician', 'necromancer', 'enchanter'],
    races: [],
    flavor: 'A straight-cut staff of ash wood, barely sanded smooth.',
    dmg: 2,
    delay: 36,
    weaponType: 'blunt',
  },

  simple_lute: {
    id: 'simple_lute',
    name: 'Simple Lute',
    slot: 'secondary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: ['bard'],
    races: [],
    flavor: 'A traveler\'s lute strung with gut strings. It carries a tune well enough.',
    dmg: 1,
    delay: 36,
    weaponType: 'blunt',
  },

  rusty_short_sword: {
    id: 'rusty_short_sword',
    name: 'Rusty Short Sword',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.5,
    classes: [],
    races: [],
    flavor: 'Pitted with rust but still functional.',
    dmg: 3,
    delay: 30,
    weaponType: 'slash',
  },

  tarnished_axe: {
    id: 'tarnished_axe',
    name: 'Tarnished Axe',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.5,
    classes: [],
    races: [],
    flavor: 'The edge is dull but the weight is substantial.',
    dmg: 4,
    delay: 32,
    weaponType: 'slash',
  },

  cracked_staff: {
    id: 'cracked_staff',
    name: 'Cracked Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.5,
    classes: [],
    races: [],
    flavor: 'Held together by will and a leather wrap.',
    dmg: 2,
    delay: 40,
    weaponType: 'blunt',
  },

  gnoll_slayer: {
    id: 'gnoll_slayer',
    name: 'Gnoll Slayer',
    slot: 'primary',
    type: 'weapon',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'bard'],
    races: [],
    flavor: 'Crafted from the fangs of a gnoll chieftain.',
    dmg: 4,
    delay: 27,
    weaponType: 'slash',
    stats: {},
  },

  // ─── SHIELDS / OFFHAND ──────────────────────────────────────────────────────

  small_shield: {
    id: 'small_shield',
    name: 'Small Shield',
    slot: 'secondary',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: [],
    races: [],
    flavor: 'A round buckler of wood banded with iron.',
    ac: 5,
  },

  // ─── ARMOR: HEAD ───────────────────────────────────────────────────────────

  cloth_cap: {
    id: 'cloth_cap',
    name: 'Cloth Cap',
    slot: 'head',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.5,
    classes: [],
    races: [],
    flavor: 'A simple woven cap that keeps the sun off and not much else.',
    ac: 1,
  },

  crude_leather_cap: {
    id: 'crude_leather_cap',
    name: 'Crude Leather Cap',
    slot: 'head',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: [],
    races: [],
    flavor: 'A stiff leather cap stitched in haste.',
    ac: 2,
  },

  // ─── ARMOR: CHEST ──────────────────────────────────────────────────────────

  cloth_tunic: {
    id: 'cloth_tunic',
    name: 'Cloth Tunic',
    slot: 'chest',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 2.0,
    classes: ['wizard', 'magician', 'necromancer', 'enchanter', 'cleric', 'druid', 'shaman', 'bard'],
    races: [],
    flavor: 'Loose linen, comfortable and breathable.',
    ac: 2,
  },

  crude_leather_tunic: {
    id: 'crude_leather_tunic',
    name: 'Crude Leather Tunic',
    slot: 'chest',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 4.0,
    classes: [],
    races: [],
    flavor: 'Stiff boiled leather pieced together with gut cord.',
    ac: 4,
  },

  // ─── ARMOR: LEGS ───────────────────────────────────────────────────────────

  cloth_pants: {
    id: 'cloth_pants',
    name: 'Cloth Pants',
    slot: 'legs',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: [],
    races: [],
    flavor: 'Plain woven trousers. Little protection but better than nothing.',
    ac: 1,
  },

  // ─── ARMOR: FEET ───────────────────────────────────────────────────────────

  simple_boots: {
    id: 'simple_boots',
    name: 'Simple Boots',
    slot: 'feet',
    type: 'armor',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.5,
    classes: [],
    races: [],
    flavor: 'Soft-soled leather boots worn smooth at the heel.',
    ac: 1,
  },

  // ─── JEWELRY ───────────────────────────────────────────────────────────────

  fishbone_earring: {
    id: 'fishbone_earring',
    name: 'Fishbone Earring',
    slot: 'ear1',
    type: 'jewelry',
    rarity: 'named',
    lore: true,
    nodrop: true,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A strange earring made from fish bones. Allows breathing underwater.',
    stats: {},
    effect: 'Enduring Breath',
  },

  glowing_black_stone: {
    id: 'glowing_black_stone',
    name: 'Glowing Black Stone',
    slot: 'ring1',
    type: 'jewelry',
    rarity: 'rare',
    lore: true,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A smooth obsidian stone that pulses with dark energy.',
    stats: { INT: 9 },
    resists: { magic: 10, fire: 0, cold: 0, poison: 0, disease: 0 },
  },

  // ─── MATERIALS / LOOT ──────────────────────────────────────────────────────

  bone_chips: {
    id: 'bone_chips',
    name: 'Bone Chips',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Cracked bones from an undead creature.',
  },

  gnoll_tooth: {
    id: 'gnoll_tooth',
    name: 'Gnoll Tooth',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Sharp and yellowed.',
  },

  gnoll_fang: {
    id: 'gnoll_fang',
    name: 'Gnoll Fang',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A curved fang from an adult gnoll.',
  },

  fire_beetle_eye: {
    id: 'fire_beetle_eye',
    name: 'Fire Beetle Eye',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Used in alchemy. Warm to the touch.',
  },

  bat_wing: {
    id: 'bat_wing',
    name: 'Bat Wing',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Thin and membranous.',
  },

  wolf_pelt: {
    id: 'wolf_pelt',
    name: 'Wolf Pelt',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.5,
    classes: [],
    races: [],
    flavor: 'A grey pelt, still warm.',
  },

  bear_pelt: {
    id: 'bear_pelt',
    name: 'Bear Pelt',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: [],
    races: [],
    flavor: 'A thick, heavy pelt.',
  },

  rat_pelt: {
    id: 'rat_pelt',
    name: 'Rat Pelt',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.3,
    classes: [],
    races: [],
    flavor: 'Small and mangy.',
  },

  snake_scale: {
    id: 'snake_scale',
    name: 'Snake Scale',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'Smooth and iridescent.',
  },

  // ─── CURRENCY ──────────────────────────────────────────────────────────────

  silver_coin: {
    id: 'silver_coin',
    name: 'Silver Coin',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.01,
    classes: [],
    races: [],
    flavor: 'Standard silver coinage.',
  },

  copper_coin: {
    id: 'copper_coin',
    name: 'Copper Coin',
    slot: 'inventory',
    type: 'material',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.01,
    classes: [],
    races: [],
    flavor: 'Worn copper currency.',
  },

  // ─── BAGS ──────────────────────────────────────────────────────────────────

  small_pouch: {
    id: 'small_pouch',
    name: 'Small Pouch',
    slot: 'bag',
    type: 'bag',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.5,
    capacity: 4,
    weightReduction: 0,
    classes: [],
    races: [],
    flavor: 'A simple cloth pouch. Holds a few items.',
  },

  large_pouch: {
    id: 'large_pouch',
    name: 'Large Pouch',
    slot: 'bag',
    type: 'bag',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 1.0,
    capacity: 8,
    weightReduction: 0,
    classes: [],
    races: [],
    flavor: 'A large leather pouch with several compartments.',
  },

  travelers_pack: {
    id: 'travelers_pack',
    name: "Traveler's Pack",
    slot: 'bag',
    type: 'bag',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 2.0,
    capacity: 10,
    weightReduction: 10,
    classes: [],
    races: [],
    flavor: "A well-crafted adventurer's pack. Items inside weigh a bit less.",
  },

  gnoll_hide_sack: {
    id: 'gnoll_hide_sack',
    name: 'Gnoll Hide Sack',
    slot: 'bag',
    type: 'bag',
    rarity: 'magic',
    lore: false,
    nodrop: false,
    weight: 1.5,
    capacity: 6,
    weightReduction: 20,
    classes: [],
    races: [],
    flavor: 'Crude but effective. Smells of wet dog.',
  },

  bread_loaf: {
    id: 'bread_loaf',
    name: 'Bread Loaf',
    slot: 'inventory',
    type: 'food',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    ac: 0,
    classes: [],
    races: [],
    flavor: 'A fresh-baked loaf from the bakers of Qeynos. Restores your strength.',
  },

  giant_snake_fang: {
    id: 'giant_snake_fang',
    name: 'Giant Snake Fang',
    slot: 'inventory',
    type: 'loot',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 0.5,
    classes: [],
    races: [],
    flavor: 'A yellowed fang from a Blackburrow constrictor. Prized by alchemists.',
  },

  blackburrow_stout: {
    id: 'blackburrow_stout',
    name: 'Blackburrow Stout',
    slot: 'inventory',
    type: 'loot',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: [],
    races: [],
    flavor: 'A cask of thick, bitter gnoll brew. Smells terrible. Worth coin to collectors.',
  },

  gold_coin: {
    id: 'gold_coin',
    name: 'Gold Coin',
    slot: 'inventory',
    type: 'currency',
    rarity: 'common',
    lore: false,
    nodrop: false,
    weight: 0.1,
    classes: [],
    races: [],
    flavor: 'A shining gold coin.',
  },

  spiked_collar: {
    id: 'spiked_collar',
    name: 'Spiked Collar',
    slot: 'neck',
    type: 'armor',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 1.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'monk', 'bard', 'berserker', 'beastlord'],
    races: [],
    flavor: 'A gnoll-crafted collar studded with bone spikes.',
    ac: 3,
    stats: { STR: 3 },
  },

  gnoll_hide_lariat: {
    id: 'gnoll_hide_lariat',
    name: 'Gnoll Hide Lariat',
    slot: 'primary',
    type: 'weapon',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 3.0,
    classes: ['warrior', 'paladin', 'shadowknight', 'ranger', 'rogue', 'bard', 'beastlord', 'monk'],
    races: [],
    flavor: 'A short whip braided from gnoll hide. Crude but effective.',
    dmg: 3,
    delay: 30,
    weaponType: 'slash',
    stats: {},
  },

  runed_totem_staff: {
    id: 'runed_totem_staff',
    name: 'Runed Totem Staff',
    slot: 'primary',
    type: 'weapon',
    rarity: 'uncommon',
    lore: false,
    nodrop: false,
    weight: 6.0,
    classes: ['cleric', 'druid', 'shaman', 'necromancer', 'wizard', 'magician', 'enchanter'],
    races: [],
    flavor: 'A carved totem staff crackling with latent gnoll magic.',
    dmg: 9,
    delay: 40,
    weaponType: 'blunt',
    stats: { hp: 5, mana: 5 },
  },
};

const STARTING_GEAR = {
  warrior:     ['short_sword', 'small_shield', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  paladin:     ['short_sword', 'small_shield', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  shadowknight:['short_sword', 'small_shield', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  berserker:   ['hatchet', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  rogue:       ['dagger', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  monk:        ['fists', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  ranger:      ['short_sword', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  bard:        ['short_sword', 'simple_lute', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  beastlord:   ['crude_spear', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  wizard:      ['gnarled_staff', 'cloth_cap', 'cloth_tunic', 'cloth_pants', 'simple_boots'],
  magician:    ['gnarled_staff', 'cloth_cap', 'cloth_tunic', 'cloth_pants', 'simple_boots'],
  necromancer: ['gnarled_staff', 'cloth_cap', 'cloth_tunic', 'cloth_pants', 'simple_boots'],
  enchanter:   ['gnarled_staff', 'cloth_cap', 'cloth_tunic', 'cloth_pants', 'simple_boots'],
  cleric:      ['crude_mace', 'small_shield', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
  druid:       ['crude_staff', 'cloth_cap', 'cloth_tunic', 'cloth_pants', 'simple_boots'],
  shaman:      ['crude_staff', 'cloth_cap', 'crude_leather_tunic', 'cloth_pants', 'simple_boots'],
};

function getItemById(id) {
  return ITEMS[id] || null;
}

function createInventoryStack(itemId, quantity = 1) {
  return { itemId, quantity, item: ITEMS[itemId] };
}

if (typeof module !== 'undefined') module.exports = { ITEMS, STARTING_GEAR, getItemById, createInventoryStack };
